openshift-kuryr-kubernetes.spec
Adding a `%global commit` line for tracking the commit that's used in the OCP RPM build.
Similar to https://github.com/openshift/origin/blob/d216153c4bcb0988564daa3bb04a6985560cc8ee/origin.spec#L13
=> %commit in openshift-kuryr-kubernetes.spec

openshift-kuryr-kubernetes.spec, tools/build-rpm.sh
Seems like in OKD builds we don't have the RPM version overwritten when
rpmbuild is exectued, so we need to keep it updated manually. This
commit updates master to set RPM version to 4.2.
=> Update RPM spec to specify 4.2 as version

openshift-kuryr-cni-ci.Dockerfile, openshift-kuryr-controller-ci.Dockerfile
This removes the workaround that injects the RDO repositories as
OpenStack mirrors were missing from OpenShift buildsystem. It's now
resolved.
=> Remove RDO repos workaround

openshift-kuryr-kubernetes.spec, openshift-kuryr-tester.Dockerfile, tools/build-rpm.sh
This commit bumps the version in the RPM spec to force the built RPM to
be preferred over the ones that are already in the repository.
=> Bump the RPM version in the spec

openshift-kuryr-cni-ci.Dockerfile, openshift-kuryr-cni.Dockerfile, openshift-kuryr-controller-ci.Dockerfile, openshift-kuryr-controller.Dockerfile, openshift-kuryr-kubernetes.spec, openshift-kuryr-tester.Dockerfile, tools/build-rpm.sh
This PR updates necessary versions and adds some hacks required to build Kuryr containers against 3.11 buildsystem.
=> 3.11 buildsystem fixes

kuryr_kubernetes/clients.py, kuryr_kubernetes/config.py, kuryr_kubernetes/tests/unit/test_clients.py
As OpenShift builds of kuryr-kubernetes use OSP14 as a base, we get
outdated kuryr.lib. In order to add latest fix that adds `region_name`
to Neutron client creation, this commit copies required functions
directly into kuryr-kubernetes code.
kuryr.lib was a mistaken experiment anyway.
=> Copy config options from kuryr-lib directly here

openshift-kuryr-kubernetes.spec
Seems like for 3.11 we only have python-setuptools RPM package and
python2-setuptools is missing. This commit switches to use the latter.
=> Install python-setuptools, not python2-setuptools

kuryr_kubernetes/controller/drivers/lbaasv2.py
keystoneauth 3.10.0 has a nasty bug preventing us from getting version
of Queens Octavia's, and it's only fixed in 3.11.0 [1] which we don't
yet have in the deps. This commit adds some protection against that.
[1] https://opendev.org/openstack/keystoneauth/commit/c40eb2951d5cf24589ea357a11aa252978636020
=> Protect from keystoneauth 3.10.0 bug

kuryr_kubernetes/controller/drivers/network_policy_security_groups.py, kuryr_kubernetes/controller/drivers/utils.py
We are retrieving the pod IP from a nonexistent annotation
field, when should be from the annotations in the pod metadata.
Also, when this information is not present we keep retrying with
the same pod object, which doesn't contains an annotation
causing the controller restart.
=> Bug 1756312: Ensure pod IP is retrieved from annotation

kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/controller/drivers/utils.py, kuryr_kubernetes/controller/handlers/pod_label.py, kuryr_kubernetes/controller/handlers/policy.py, kuryr_kubernetes/controller/handlers/vif.py, kuryr_kubernetes/tests/unit/controller/handlers/test_policy.py
When a Network Policy is enforced we shouldn't try to update the
SG of a LBaaS that would map to a SVC without selector, as this
kind of SVC is not wired by Kuryr. Also, we shouldn't try to update
the LBaaS SG when no ports are defined in the SVC spec.
=> Bug 1756981: Ensure no LBaaS SG update is triggered for SVCs without selectors and ports

kuryr_kubernetes/controller/drivers/network_policy_security_groups.py, kuryr_kubernetes/controller/handlers/namespace.py, kuryr_kubernetes/tests/unit/controller/handlers/test_namespace.py
This patch ensures lb sg rules are updated when NPs reference to
namespace labels through namespace selectors. The affected svc
will be updated after namespace label is updated and due to that it
either starts or stops being referenced by the NP.
=> Bug 1757141: Ensure lb sg rules are updated upon namespace label updates

kuryr_kubernetes/controller/drivers/base.py, kuryr_kubernetes/controller/drivers/vif_pool.py, kuryr_kubernetes/controller/handlers/policy.py, kuryr_kubernetes/tests/unit/controller/handlers/test_policy.py
When a NP is deleted its associated SG should be deleted too.
However, when using pools, ports may have that SG assigned, not
allowing the SG deletion and consequently stoping the kuryrnetpolicy
associated object deletion -- which may cause kuryr-controller crashes
too
=> Bug 1758528: Ensure ports from pool do not reference deleted SGs/NPs

kuryr_kubernetes/controller/drivers/namespace_subnet.py, kuryr_kubernetes/controller/drivers/network_policy_security_groups.py, kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/controller/handlers/namespace.py, kuryr_kubernetes/controller/handlers/pod_label.py, kuryr_kubernetes/controller/handlers/vif.py, kuryr_kubernetes/handlers/retry.py, kuryr_kubernetes/tests/unit/handlers/test_retry.py, kuryr_kubernetes/utils.py
There are different races conditions between retry actions (activation vif, getting vif for a pod, ...) and deletion actions. It may happen that some retry action gets postponed until the resource has already been deleted, leading to kuryr-controller errors.
=> Bug 1759984: Fix race conditions between handling ResourceNotReady and deletions

kuryr_kubernetes/controller/drivers/nested_vlan_vif.py, kuryr_kubernetes/controller/drivers/neutron_vif.py, kuryr_kubernetes/controller/drivers/vif_pool.py, kuryr_kubernetes/tests/unit/controller/drivers/test_nested_vlan_vif.py
This PS ensures that kuryr-controller does not crash if neutron
cannot be reached to check the port status, or if neutron replies
with unexpected error when trying to add ports to the trunks
=> Bug 1761505: Avoid controller crash upon unexpected neutron error handling ports

kuryr_kubernetes/controller/drivers/namespace_subnet.py, kuryr_kubernetes/controller/handlers/namespace.py, kuryr_kubernetes/tests/unit/controller/handlers/test_namespace.py
When a namespace is deleted, kuryr-controller is in charge of
deleting its associated openstack resources (net, subnet and ports)
as well as the associated KuryrNet CRD.
As removing OpenStack resources may take some time, if the
kuryr-controller is restarted by any different reason during that
process, the resources will be left behind as no new events for the
namespace (already deleted) will happen after the restart. This
patch fixes this problem by ensuring upon reboot that there are no
orphan KuryrNet CRDs for unexisting namespaces, and deleting them
in case there are (including its associated OpenStack resources).
=> Bug 1763278: Remove namespace leftover upon kuryr-controller restart

kuryr_kubernetes/controller/drivers/nested_vlan_vif.py, kuryr_kubernetes/controller/drivers/neutron_vif.py, kuryr_kubernetes/controller/drivers/vif_pool.py, kuryr_kubernetes/tests/unit/controller/drivers/test_nested_vlan_vif.py
This PS ensures that kuryr-controller does not crash if neutron
cannot be reached to check the port status, or if neutron replies
with unexpected error when trying to add ports to the trunks
This PR combines #63 and #70 as those are related to one bugreport.
=> [release-4.2] Bug 1761507: Avoid controller crash upon unexpected neutron error handling ports

openshift-kuryr-cni-ci-rhel8.Dockerfile, openshift-kuryr-cni-rhel8.Dockerfile, openshift-kuryr-controller-ci-rhel8.Dockerfile, openshift-kuryr-controller-rhel8.Dockerfile, openshift-kuryr-kubernetes-rhel8.spec, openshift-kuryr-tester-rhel8.Dockerfile, tools/build-rpm-rhel8.sh
In order to have the latest possible dependencies, this commit switches
Kuryr images to use RHEL8 and OSP16.
=> Switch to RHEL8 and OSP16

kuryr_kubernetes/controller/drivers/lbaasv2.py
This reverts commit 819d0c0ff4f5ab51fef223efa0ee76e8f66167a1. We now
build with keystoneauth 3.17.1, so this should be safe to revert. This
resolves #37.
Change-Id: I3fd5dc90cfc3333ef294f6dc89833faa7bdf550c
=> Revert "Protect from keystoneauth 3.10.0 bug"

kuryr_kubernetes/clients.py, kuryr_kubernetes/config.py, kuryr_kubernetes/tests/unit/test_clients.py
With OSP16 version of kuryr-lib we should be able to revert copying its options inside kuryr-kubernetes code.
=> Revert "Copy config options from kuryr-lib directly here"

kuryr_kubernetes/controller/drivers/vif_pool.py
We should ensure the ports pools dict that is being
interated do not change over time, causing the deletion
of the ports to fail. A dict copy is made to avoid this.
=> Bug 1777509: Fix deletion of ports on a pool

kuryr_kubernetes/controller/drivers/vif_pool.py, kuryr_kubernetes/tests/unit/controller/drivers/test_vif_pool.py
This patch ensures there is no pool repopulation triggered before
the pools are recovered upon a kuryr-controller restart
=> Bug 1776894: Ensure pools population does not happen until pools are recovered

kuryr_kubernetes/cmd/webhook_server.py, kuryr_kubernetes/config.py, kuryr_kubernetes/tests/unit/cmd/test_status.py, kuryr_kubernetes/tests/unit/test_k8s_client.py
This PR ensure that Kuryr-admission-controller is up and ready (including its associated service) before other operators so that the proper dns configuration is enforced
=> Bug 1754046: Ensure kuryr webhook is running before other operators' pods

kuryr_kubernetes/cni/binding/base.py, kuryr_kubernetes/cni/binding/bridge.py, kuryr_kubernetes/cni/binding/nested.py, kuryr_kubernetes/tests/unit/cni/test_binding.py
If kuryr-daemon was restarted during nested interface binding, after the
pod interface got created, but before returning to kubelet, such a
request will get retried by kubelet. As the interface with either
vif.vif_name or CNI request's ifname will already exist in the pod
namespace, the call will fail with NetlinkError: (17, 'File exists').
To prevent that this commit adds a check for such interfaces. If they
exist - they got removed before the real binding starts.
Change-Id: Iaa4d472fb4681e4d9af93561bdccdcb62ce500a0
=> Bug 1779163: Nested CNI: Look for leftover ifaces to remove

kuryr_kubernetes/controller/drivers/lbaasv2.py
In case an endpoint is not yet annotated with the lbaas
state, when a Network Policy enforcement is triggered,
the update of the lbaas SG is ignored, causing a security breach.
This commit fixes the issue by retrying the update of the sg.
Change-Id: I4ebb8d5da52ff2cee8970b061e31b3f391cacc1b
=> Bug 1786299: Ensure LB sg update is retried when NP is enforced

kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/tests/unit/controller/handlers/test_lbaas.py
When pods that run on host network and are pointed by a svc
are removed, the removal of the load balancer member is
ignored, as right now the name of the pod is not taken into
account on the decision of which members to delete, and the
current attributes checked are pod ip and port, which remains
the same. This commit fixes the issue by ensuring the
pod name is also checked.
Change-Id: I44f7f76da692ac3002c91a1420969584b4d31cbd
=> Bug 1786140: Ensure LB member is removed upon pod removal

kuryr_kubernetes/controller/handlers/namespace.py
This patch ensures that network leftovers without kuryrnet CRD
object associated (caused by crash/restart of the kuryr-controller
at an unfortunate time) are also handled by the cleanup thread
triggered at the kuryr-controller restart.
Change-Id: Id1d036b80438b21a100be12282058b995c36d2c3
=> Bug 1785136: Ensure network leftovers without kuryrnet CRD obj are deleted

kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
For some reason openstacksdk/keystoneauth1 get_api_major_version()
started to return the minimum version for the endpoint. Also trying to
specify min_version makes the call to fail with string parsing
exception. To fix it this commit uses get_all_version_data() instead and
parses the results internally in Kuryr.
Change-Id: I19823fa2164e6565ee6560706585abec1a88f16d
=> Bug 1788634: Fix Octavia version detection

kuryr_kubernetes/controller/drivers/lbaasv2.py, releasenotes/notes/octavia-acls-7452d3406d75ea15.yaml
Since Train, Octavia has a new API to restrict lbs access on
listeners. This is important when enforcing Network Policies
on services.
Before this patch, Kuryr required either admin priviledges to
change the security group rules associated to the loadbalancer,
or use the ovn-octavia loadbalancer that does not require those
rules as the source IP is not changed when passing through the
LoadBalancer VIP.
By adopting the new Octavia ACL API, there is no need for admin
priviledges to limit the access to the loadbalancers.
Change-Id: I8f6bae00413aa181e9c2cac72c87bd93161796bc
=> Bug 1788650: Add support to Octavia ACLs

kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/controller/handlers/lbaas.py
Due to a bug in Octavia this was previously avoided. This is now
supported for the amphora provider, so it won't be blocked on the
kuryr side
Change-Id: If7d32023e467d1a63812057e1d151901ce462c7f
=> Bug 1791277: Add support for listeners on the same port but different protocol

kuryr_kubernetes/controller/drivers/vif_pool.py
It seems that when an namespace deletion fails for some reason and
it is retried, if there are other NPs created, some of the unused
ports can be reused and moved from one sg_key to another, therefore
raising the KeyError on the retry.
This patch ensure that if the sg_key was already deleted, the retry
skips it instead of failing
Change-Id: Ifcebf7660861738128606342dc6dab00186878b5
=> Bug 1792239: Avoid KeyError when deleting NPs

kuryr_kubernetes/controller/drivers/lbaasv2.py
When enforce_sg_rules is not set the member creation should not trigger
loadbalancer security group rules update. This patch ensures the
action is not triggered in such a case.
Change-Id: I0d5f6ffd47fe0a1ae998aa4a61a9240ce0accd40
=> Bug 1788650: Ensure lb SG is not updated on member creation

kuryr_kubernetes/controller/handlers/namespace.py, kuryr_kubernetes/controller/handlers/policy.py, kuryr_kubernetes/controller/handlers/vif.py, kuryr_kubernetes/controller/managers/health.py, kuryr_kubernetes/opts.py, kuryr_kubernetes/tests/unit/controller/managers/test_health.py, kuryr_kubernetes/utils.py, releasenotes/notes/deprecate-handlers-caching-9cdfd772aba9a7ce.yaml
Current deployments of OpenShift platform with Kuryr CNI
in real OpenStack installations (multi-projects environments)
are crashing because of kuryr-controller cannot come to
READY state.
This is due to inaccurate quota calculations in the readiness
process and an unscalable fetching of objects from Neutron API
to count and comparing with limits.
This commit ensures accurate quota calculation for installation
project during the readiness checks and removes the harsh
Neutron API calls. It will dramatically speedup readiness checks.
=> Bug 1810501:  Ensures accurate quota calculation during the readiness checks 

kuryr_kubernetes/controller/drivers/network_policy_security_groups.py, kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy_security_groups.py
Right now we attempt to retrieve the list of pods without
fetching the items field returned on the kubernetes response,
causing the wrong element to be fetched.
This commit fixes the issue by getting the list of pods
through the items.
=> Bug 1810517: Ensure list of pods items is retrieved

kuryr_kubernetes/k8s_client.py, kuryr_kubernetes/tests/unit/test_k8s_client.py
Seems like K8sClient wasn't raising K8sResourceNotFound exception on 404
from all the methods, e.g. patch. This commit makes sure that is no
longer the case and any 404 results in K8sResourceNotFound exception.
=> Bug 1810571: Raise K8sResourceNotFound for all client methods

kuryr_kubernetes/cni/binding/nested.py, kuryr_kubernetes/tests/unit/cni/test_binding.py
Historically we haven't been doing any actions on CNI DEL request when
running in nested mode because all the interfaces we created will be
gone when netns will get deleted. There is an issue with that approach:
1. We get ADD request for pod A in netns X and correctly bind it using
VLAN ID V.
2. We get DEL request for same pod A and netns X. We don't do anything.
3. Netns is not yet deleted…
4. Another ADD request comes for pod A but now with netns Y (normal K8s
behavior).
a) We try binding it, but there is a veth pair with VLAN ID V already
on the host namespace, so we end up with VLAN ID conflict.
b) Binding fails with EEXIST error.
The problem with this hypothesis is that the EEXIST error seems to be
persistent and in theory it should disappear after the netns gets
deleted but maybe …
=> Bug 1810574: Nested CNI: Remove interfaces on DEL requests

kuryr_kubernetes/cmd/gather_openstack_data.py, openshift-kuryr-kubernetes-rhel8.spec, setup.cfg
This commit ensures all the OpenStack resources data handled
in Kuryr is gathered.
=> Gather OpenStack resources data

kuryr_kubernetes/cmd/webhook_server.py
Kuryr's webhook is now updated to use stable API. In that version the
validation of the webhook's response is more strict and we need to
return correct apiVersion and kind along with the response. This commit
makes sure we do that.
=> Kuryr: Add apiVersion and kind to AC reponse

kuryr_kubernetes/controller/handlers/namespace.py, kuryr_kubernetes/controller/handlers/policy.py, kuryr_kubernetes/controller/handlers/vif.py, kuryr_kubernetes/controller/managers/health.py, kuryr_kubernetes/opts.py, kuryr_kubernetes/tests/unit/controller/managers/test_health.py, kuryr_kubernetes/utils.py, releasenotes/notes/deprecate-handlers-caching-9cdfd772aba9a7ce.yaml
Current deployments of OpenShift platform with Kuryr CNI
in real OpenStack installations (multi-projects environments)
are crashing because of kuryr-controller cannot come to
READY state.
This is due to inaccurate quota calculations in the readiness
process and an unscalable fetching of objects from Neutron API
to count and comparing with limits.
This commit ensures accurate quota calculation for installation
project during the readiness checks and removes the harsh
Neutron API calls. It will dramatically speedup readiness checks.
Change-Id: Ia5e90d6bd5a8d30d0596508abd541e1508dc23ec
Closes-Bug: 1864327
=> [release-4.3] Bug 1815019: Ensures accurate quota calculation during the readiness checks

kuryr_kubernetes/controller/drivers/lbaasv2.py
When updating the LB security group with only the rules applied
on a Network Policy we are also considering the sg rules owned by
octavia, this result on failure when trying to delete the rules
as this operation is not allowed.
=> Bug 1818067:Ensure no attempt to deleted sg rules owned by Octavia happens

openshift-kuryr-cni-ci-rhel8.Dockerfile, openshift-kuryr-cni-rhel8.Dockerfile, openshift-kuryr-controller-ci-rhel8.Dockerfile, openshift-kuryr-controller-rhel8.Dockerfile, openshift-kuryr-kubernetes-rhel8.spec, openshift-kuryr-tester-rhel8.Dockerfile, tools/build-rpm-rhel8.sh
Current dev release is 4.5 so we should use 4.5 repos by default.
=> Bug 1826770: Update the Kuryr images to 4.5 repos

kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/tests/unit/controller/handlers/test_lbaas.py
As soon as the service is created it's possible that the backend pods
are not yet created resulting in an lbaas_spec annotation with no
security groups defined, and so security group rules can turn out
to be removed from the load balancer sg. This commit ensures the
lbaas_state annotation contains the updated sgs.
=> Bug 1824258: Ensure LB state annotation sg matches the SG on the LB

kuryr_kubernetes/controller/drivers/lbaasv2.py
This patch ensure the proper listener id is found and its associated
security groups are updated.
Change-Id: I72120c33debddfe6ba29c8c0152a0cef4e96a6eb
Closes-Bug: 1875428
=> Bug 1828387: Ensure NP are enforced on SVC with different port and target port

openshift-kuryr-tester.Dockerfile, tox.ini
This commit pins the dependecies to Stein release, as the controller
image also uses it, and upgrades pip.
=> Bug 1836187: Fix Kuryr CI for 3.11 branch

kuryr_kubernetes/controller/drivers/namespace_security_groups.py, kuryr_kubernetes/tests/unit/controller/drivers/test_namespace_security_groups.py
Namespace isolation does not handle egress, so there is no need
to keep the egress rules on the namespace associated security
groups. This is left to the default SG group and or to the customer
to modified the needed SG egress rules on the namespaces as needed.
It also adds the possibility of not only have the "default" namespace
as exception for the isolation.
=> Namespace SG driver: remove default egress rules

kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/controller/drivers/namespace_security_groups.py
This patch removes the usage of remote_group_id at the loadbalancer
SG rules to allow the access to the namespace. It obtaines the
namespace associated range and use remote_ip_prefix instead.
Note remote_group_id is still used for the default and namespace
SG groups. We can improve it by replacing the rules inside those two
(which use remote_group_ids too) to use remote_ip_prefixes.
=> Remove remote_group_id usage at loadbalancer SGs

test-requirements.txt
flake8 new release 3.8.0 added new checks and gate pep8
job start failing. hacking 3.0.1 fix the pinning of flake8 to
avoid bringing in a new version with new checks.
Though it is fixed in latest hacking but 2.0 and 3.0 has cap for
flake8 as <4.0.0 which mean flake8 new version 3.9.0 can also
break the pep8 job if new check are added.
To avoid similar gate break in future, we need to bump the hacking min
version.
- http://lists.openstack.org/pipermail/openstack-discuss/2020-May/014828.html
Change-Id: I54d3d778266d840bd724836018340d9bd3987844
=> Bug 1838997: Fix hacking min version to 3.0.1

kuryr_kubernetes/controller/drivers/lbaasv2.py
When a pod event is handled it's possible that a Network Policy and Service
are affected by that pod and the LB sg of selected services needs to be
updated. However, the endpoints for the matched service may not be yet
present or were deleted, resulting in a NotFound exception.
This commit handled this exception by skipping the LB sg update.
Change-Id: I21a4d6cb515633d47b534f180517687d07b8f83f
Closes-bug: 1876666
=> Bug 1838985:Skip LB sg update when no endpoint is found

kuryr_kubernetes/cni/daemon/service.py, kuryr_kubernetes/cni/plugins/k8s_cni_registry.py, kuryr_kubernetes/tests/unit/cni/plugins/test_k8s_cni_registry.py, kuryr_kubernetes/tests/unit/cni/test_service.py
In highly distributed environment like Kubernetes installation with
Kuryr, we need to plan for network outages in any case. If we don't, we
end up with bugs like one this patch tries to fix.
If we'd lose a Pod delete event on kuryr-daemon following can happen:
1. Pod A of name "foo" gets created.
2. It gets annotated normally and CNI ADD request gives it an IP X.
3. Pod A gets deleted.
4. Somehow the delete event gets lost on kuryr-daemon's watcher.
5. CRI sends CNI DEL request and pod gets unplugged successfully. It
never gets deleted from the daemon's registry, because we never
got the Pod delete event from K8s API.
6. Pod B of the same name "foo" gets created.
7. CNI looks up registry by <namespace>/<pod>, finds old VIF there
and plugs pod B with pod A's VIF X.
8. kuryr-controller …
=> Bug 1810574: CNI: Confirm pods in cache before connecting

kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
In case a LB resource ends up with ERROR in the provisioning status
we must ensure the deletion and recreation of the resource.
Closes-bug: 1879371
Change-Id: I2531948ab6181cfa5049b54c78935c23f60173d2
=> Bug 1840187:Ensure LB resources with ERROR status are deleted

kuryr_kubernetes/config.py, kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/controller/handlers/lbaas.py, releasenotes/notes/deprecate-sg-mode-option-96824c33335cd74b.yaml
When deleting services and the respective load balancer
with using ovn-octavia provider, the lb sg is not deleted.
This commit fixes the issue by removing the LB sg creation
when the octavia provider is ovn-octavia, as that sg is not
really enforced.
Closes-bug: 1880207
Change-Id: I2c77b1d0ac682008ff6c31781d6075c208c689d0
=> Bug 1839180: Remove lb sg creation when octavia provider is ovn-octavia

kuryr_kubernetes/config.py, kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/controller/handlers/lbaas.py, releasenotes/notes/deprecate-sg-mode-option-96824c33335cd74b.yaml
When deleting services and the respective load balancer
with using ovn-octavia provider, the lb sg is not deleted.
This commit fixes the issue by removing the LB sg creation
when the octavia provider is ovn-octavia, as that sg is not
really enforced.
Closes-bug: 1880207
Change-Id: I2c77b1d0ac682008ff6c31781d6075c208c689d0
=> Bug 1841493: Remove lb sg creation when octavia provider is ovn-octavia

openshift-kuryr-cni-ci-rhel8.Dockerfile, openshift-kuryr-cni-rhel8.Dockerfile, openshift-kuryr-controller-ci-rhel8.Dockerfile, openshift-kuryr-controller-rhel8.Dockerfile, openshift-kuryr-kubernetes-rhel8.spec, openshift-kuryr-tester-rhel8.Dockerfile, tools/build-rpm-rhel8.sh
The master branch is 4.6 now, this commit updates versions and used
repositories to 4.6.
=> Bump versions to 4.6

kuryr_kubernetes/controller/handlers/kuryrnetwork.py
This patch ensures if on_finalize event for a CR is processed before
its status got populated, it is still possible to remove its finalizer
and unblock the namespace deletion.
Change-Id: I338ad6967f96807431754e91d2c1f9031723ec8e
Closes-Bug: 1881318
=> Bug 1841846: Ensure kuryrnetwork CRs without status can be deleted

kuryr_kubernetes/objects/lbaas.py, kuryr_kubernetes/tests/unit/test_object.py
When no security groups is present on the LBaaSLoadBalancer oslo
versioned object it should default to an empty list and not to
None. Otherwise iterations of the security_groups field fails.
Closes-bug: 1881575
Change-Id: I9a98584f80219bf5c2ea414177826a26470d414f
=> Bug 1843674: Ensure security_groups on LBaaSLoadBalancer defaults to empty list

kuryr_kubernetes/clients.py
As openstacksdk 0.36.0 is needed on lower-constraints and it
does not support allowed_cidrs field on the listener, we must
ensure that field is present to properly update the listeners ACLs.
Closes-bug: 1881914
Change-Id: I46d14e9088a0643ba02b0a7d4c8000fa2a22d379
=> Bug 1843813: Ensure allowed_cidrs field is present on older openstacksdk versions

openshift-kuryr-kubernetes-rhel8.spec, tools/build-rpm-rhel8.sh
This commit makes sure we're getting the version to use as RPM and
Python package semver from the last tag in git. This should solve issue
of `kuryr-k8s-controller --version` returning 0.0.0 and remove the need
to update versions in various places each time master gets opened to new
release development.
=> Bug 1843342: Get RPM and Kuryr version from git 

kuryr_kubernetes/cni/binding/nested.py, kuryr_kubernetes/cni/daemon/service.py, kuryr_kubernetes/cni/plugins/k8s_cni_registry.py
We've seen some issues related to the fact that on CNI DEL we wait for
pod annotation to appear in CNI registry:
1. Overloaded kuryr-daemon HTTP server, because many stale DEL requests
from CRI will saturate the number of free connections, causing CNI to
answer requests extremely slowly.
2. Some CRI's will not delete network namespace before getting a
successful CNI DEL. If we'll assign the same IP (or vlan) to a next
pod, we might end up with an IP or vlan conflict and NetlinkError.
This commit makes sure we only wait for VIFs up to 5 seconds on DEL
requests, enough time for watcher to populate registry on restart. Also
some code got moved around to make implementating the above simpler and
some logs got clarified to make debugging of such issues easier later
on.
Change-Id: …
=> Bug 1846225: CNI: Don't wait for missing pods on DEL

openshift-kuryr-kubernetes-rhel8.spec, tools/build-rpm-rhel8.sh
This commit makes sure we're getting the version to use as RPM and
Python package semver from the last tag in git. This should solve issue
of `kuryr-k8s-controller --version` returning 0.0.0 and remove the need
to update versions in various places each time master gets opened to new
release development.
=> Bug 1845914: Get RPM and Kuryr version from git

kuryr_kubernetes/controller/drivers/lbaasv2.py
ovn-octavia provider now can handle listeners on the same port
for both udp and tcp
Change-Id: I9d5e9bb9219c2d1eaca8ed43633bd41f428b2a4e
=> Bug 1846396: Remove ovn-octavia provider tcp+udp limitation

kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/tests/unit/controller/handlers/test_lbaas.py
Upon kuryr-controller restart, if kuryr configuration regarding
octavia provider has changed, the cleanup process not only
removes the leftovers loadbalancers but also:
- remove the lbs with the previous octavia provider driver
- modifies endpoints annotations (provider information) to force
the recreation of the loadbalancer with the new provider
Change-Id: I78fd6bdd1f53ea8eb2ba85395fd2e3c651487c60
=> Bug 1846862: Add support for amphora to ovn-octavia upgrade

kuryr_kubernetes/controller/drivers/sriov.py, kuryr_kubernetes/controller/drivers/utils.py, kuryr_kubernetes/utils.py, test-requirements.txt
flake8 new release 3.8.0 added new checks and gate pep8
job start failing. hacking 3.0.1 fix the pinning of flake8 to
avoid bringing in a new version with new checks.
Though it is fixed in latest hacking but 2.0 and 3.0 has cap for
flake8 as <4.0.0 which mean flake8 new version 3.9.0 can also
break the pep8 job if new check are added.
To avoid similar gate break in future, we need to bump the hacking min
version.
- http://lists.openstack.org/pipermail/openstack-discuss/2020-May/014828.html
Change-Id: I54d3d778266d840bd724836018340d9bd3987844
=> Bug 1847105: Fix hacking min version to 3.0.1

kuryr_kubernetes/cni/binding/nested.py, kuryr_kubernetes/cni/daemon/service.py, kuryr_kubernetes/cni/plugins/k8s_cni_registry.py
We've seen some issues related to the fact that on CNI DEL we wait for
pod annotation to appear in CNI registry:
1. Overloaded kuryr-daemon HTTP server, because many stale DEL requests
from CRI will saturate the number of free connections, causing CNI to
answer requests extremely slowly.
2. Some CRI's will not delete network namespace before getting a
successful CNI DEL. If we'll assign the same IP (or vlan) to a next
pod, we might end up with an IP or vlan conflict and NetlinkError.
This commit makes sure we only wait for VIFs up to 5 seconds on DEL
requests, enough time for watcher to populate registry on restart. Also
some code got moved around to make implementating the above simpler and
some logs got clarified to make debugging of such issues easier later
on.
Change-Id: …
=> Bug 1779163: CNI: Don't wait for missing pods on DEL

openshift-kuryr-kubernetes-rhel8.spec, tools/build-rpm-rhel8.sh
This commit makes sure we're getting the version to use as RPM and
Python package semver from the last tag in git. This should solve issue
of `kuryr-k8s-controller --version` returning 0.0.0 and remove the need
to update versions in various places each time master gets opened to new
release development.
=> Bug 1845921: Get RPM and Kuryr version from git

kuryr_kubernetes/config.py, kuryr_kubernetes/handlers/asynchronous.py, kuryr_kubernetes/handlers/base.py, kuryr_kubernetes/handlers/dispatch.py, kuryr_kubernetes/handlers/k8s_base.py, kuryr_kubernetes/handlers/logging.py, kuryr_kubernetes/handlers/retry.py, kuryr_kubernetes/tests/unit/handlers/test_asynchronous.py, kuryr_kubernetes/tests/unit/test_watcher.py, kuryr_kubernetes/watcher.py, lower-constraints.txt, requirements.txt
Kuryr-Kubernetes relies on watching resources in K8s API using an HTTP
stream served by kube-apiserver. In such a distributed system this is
sometimes unstable and e.g. etcd issues can cause some events to be
omitted. To prevent controller from such situations this patch makes
sure that periodically a full list of resources is fetched and injected
as events into the handlers.
We should probably do the same for kuryr-daemon watcher, but that case
is less problematic as it'll be restarted in event of ADD requests
timing out.
=> Bug 1847011: Periodically fetch full list of watched resources 

openshift-kuryr-kubernetes-rhel8.spec, tools/build-rpm-rhel8.sh
This commit makes sure we're getting the version to use as RPM and
Python package semver from the last tag in git. This should solve issue
of `kuryr-k8s-controller --version` returning 0.0.0 and remove the need
to update versions in various places each time master gets opened to new
release development.
=> Bug 1845923: Get RPM and Kuryr version from git

openshift-kuryr-kubernetes-rhel8.spec
We've got versions of dependencies in the RPM spec a bit out of sync
with reqirements.txt. This may cause issues if some packages in the
repos we use get downgraded as we won't notice that at build time.
This commit synchronizes versions in RPM spec.
=> Sync RPM spec dependencies with requirements.txt

openshift-kuryr-kubernetes-rhel8.spec
We don't have pyroute2 0.5.7 in OpenStack repos we use, we need to
downgrade the requirement to 0.5.6. The reason mistake got through the
CI is that dnf just installed older version of the Kuryr RPM that was in
the plashet and wasn't yet requiring pyroute2 that was not available.
=> Fix RPM spec pyroute2 version

kuryr_kubernetes/tests/unit/controller/managers/test_prometheus_exporter.py
Seems like one test is using external mock library, this commit fixes
that.
=> Fix unit tests

kuryr_kubernetes/controller/drivers/network_policy.py, kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy.py
While handling the creation of a Network
Policy it's possible that the CRD is patched
with repeated sg rules, which is not allowed
resulting in validation error as the repeated
sg rules will not have the sg rule id.
Closes-Bug: #1887167
Change-Id: Ia7814ddcea0d6948ff280a3e03a896bbc442891c
=> Bug 1856830: Fix duplicated sg rules on NP crd

kuryr_kubernetes/cni/binding/nested.py, kuryr_kubernetes/tests/unit/cni/test_binding.py
The VLAN and macvlan nested drivers are using [binding]link_iface option
to get the port they should bind the subport to. This isn't ideal as
there's a single config for all kuryr-cni containers in the cluster, so
it's impossible to provide multiple interface names when e.g. different
VM images are used to run workers in the cluster.
In order to make behavior smarter this patch makes sure that when
aforementioned option is not set, kuryr-daemon will attempt to
autodetect the interface it should bind the subport to by trying to find
which iterface kubelet is bound to. This should work fine with OpenShift
setups. If such interface is not found, kuryr-daemon will choose first
non-loopback interface.
Implements: blueprint autodetect-nested-iface
Change-Id: …
=> Bug 1855773: Attempt to autodetect interface in nested setups

kuryr_kubernetes/controller/handlers/vif.py, kuryr_kubernetes/exceptions.py, kuryr_kubernetes/k8s_client.py, kuryr_kubernetes/tests/unit/controller/handlers/test_vif.py
We were observed the situation, where pod has been created, triggered
KuryrPort CRD creation and removed just before Kuryrport on_present
event was handled, resulting in errors from KuryrPort side.
Idea is to set the finalizer to the pod as quickly as possible, so that
it wont disappear before we correctly set up the CRD.
=> Bug 1867534: Add finalizer for the pod as soon as possible.

kuryr_kubernetes/config.py, kuryr_kubernetes/handlers/asynchronous.py, kuryr_kubernetes/handlers/base.py, kuryr_kubernetes/handlers/dispatch.py, kuryr_kubernetes/handlers/k8s_base.py, kuryr_kubernetes/handlers/logging.py, kuryr_kubernetes/handlers/retry.py, kuryr_kubernetes/tests/unit/handlers/test_asynchronous.py, kuryr_kubernetes/tests/unit/test_watcher.py, kuryr_kubernetes/watcher.py, lower-constraints.txt, requirements.txt
Kuryr-Kubernetes relies on watching resources in K8s API using an HTTP
stream served by kube-apiserver. In such a distributed system this is
sometimes unstable and e.g. etcd issues can cause some events to be
omitted. To prevent controller from such situations this patch makes
sure that periodically a full list of resources is fetched and injected
as events into the handlers.
We should probably do the same for kuryr-daemon watcher, but that case
is less problematic as it'll be restarted in event of ADD requests
timing out.
Change-Id: I67874d086043071de072420df9ea5e86b3f2582e
=> Bug 1868427: Periodically fetch full list of watched resources

kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py
Currently for a pending Octavia LB being created, `update_lbaas_sg()` will raise `ResourceNotReady`, causing NetworkPolicy handling process to get postponed. There's no need to do that - once created the correct set of SGs will be determined by LB creation code itself, so there's no need to delay NP handling process. In slower environment this may even cause some NPs to be handled with massive delay.
This PR fixes that making sure we catch `ResourceNotReady` from `update_lbaas_sg()` in KuryrNetworkPolicyHandler and ignore it.
=> Bug 1869294: Ignore ResourceNotReady from update_lbaas_sg() when handling network policy

kuryr_kubernetes/controller/drivers/utils.py, kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/controller/handlers/loadbalancer.py, kuryr_kubernetes/k8s_client.py, kuryr_kubernetes/objects/lbaas.py, kuryr_kubernetes/utils.py
On upgrade from version using annotations on Endpoints and Services
objects to save information about created Octavia resources, to a
version where that information lives in KuryrLoadBalancer CRD we need to
make sure that data is converted. Otherwise we can end up with doubled
loadbalancers.
This commit makes sure data is converted before we try processing any
Service or Endpoints resource that has annotations.
Change-Id: I01ee5cedc7af8bd02283d065cd9b6f4a94f79888
=> Bug 1867520: Support upgrading LBaaSState annotation to KLB CRD

kubernetes_crds/kuryr_crds/kuryrport.yaml, kuryr_kubernetes/cni/binding/dpdk.py, kuryr_kubernetes/cni/handlers.py, kuryr_kubernetes/controller/drivers/utils.py, kuryr_kubernetes/controller/handlers/kuryrport.py, kuryr_kubernetes/controller/handlers/pod_label.py, kuryr_kubernetes/controller/handlers/vif.py, kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrport.py, kuryr_kubernetes/tests/unit/controller/handlers/test_vif.py, kuryr_kubernetes/utils.py
In newly added CRD, KuryrPort, we noticed, that vifs key, which is now
under 'spec' object, is rather a thing which could be represented as the
CRD status.
In this patch we propose to move vifs data under the status key.
=> Bug 1867538: Move vifs to 'status' in the KuryrPort CRD.

kuryr_kubernetes/controller/handlers/lbaas.py
As the Finalizer is first removed from the lb CRD and
then from the Service, we should add protection for when
the CRD is gone but the Service is still present with
the Finalizer set.
Change-Id: I9fe88bb78fea4930c241ecf1117eafecaf279c94
=> Bug 1871839: Ensure Service is delete if lb CRD is already gone

kuryr_kubernetes/cni/binding/base.py, kuryr_kubernetes/cni/plugins/k8s_cni_registry.py
It seems that latest crio versions moved removal of network namespace to
later in the container lifecycle. This means that sometimes the network
namespace of a container will hang after pod is already gone from the
API and Kuryr assigned it's VIF to another pod. This might cause VLAN ID
conflicts, but normally that's not an issue as kuryr-daemon is removing
interfaces from container namespace on CNI DEL.
It may however happen that if kuryr-daemon was down when CNI DEL
happened, the info about the VIF saved in KuryrPort will already be
gone. In that case we simply returned success to the CNI without doing
any unplugging. Now if the netns is not removed immediately after that
we might end up with VLAN ID conflicts.
This commit makes sure that even if VIF info is gone, kuryr-daemon will
at …
=> Bug 1869606: Remove the pod interface even if VIF is gone

kuryr_kubernetes/controller/handlers/kuryrport.py, kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrport.py
In case of missing pod, KuryrPort should remove itself by removing its
finalizer, not non-existent pod finalizer.
Closes-Bug: 1892863
Change-Id: I10fc315b6ff456282d71d84e6cee4c226ac5cdba
(cherry picked from commit c7fd31951b6a3121b95c81078522ad57790ad8b5)
=> Bug 1872265: Remove right finalizer on pod absence.

kuryr_kubernetes/controller/handlers/kuryrport.py, kuryr_kubernetes/controller/handlers/vif.py, kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrport.py
It might happen, that operator would manually removing KuryrPort CRD
corresponding to the pod, and than pod would become broken  - there
would be no connectivity to it.
In this patch we prevent from removing KP, in case Pod is not in
deleting state. Now, it will defer the deletion till the Pod deletion.
Change-Id: Idd6383296723c41ed6f29715969c452ef3fcdb1f
(cherry picked from commit 98c78b75bb43c093039187612af05858c139a3b8)
=> Bug 1872265: Guard against manually removing of KuryrPort CRD.

kuryr_kubernetes/controller/drivers/namespace_subnet.py, kuryr_kubernetes/controller/drivers/vif_pool.py, kuryr_kubernetes/tests/unit/controller/drivers/test_namespace_subnet.py, kuryr_kubernetes/tests/unit/controller/drivers/test_vif_pool.py
Namespace deletion can be stuck if not all the ports belonging
to the associated namespace networks are deleted.
This patch enforce proper clean up of subports by:
- Ensuring no request/release VIF actions are processed until the pools
are recovered by the controller
- Ensure if there are subports leftover when removing a namespace those
are detached from the pool and deleted regardless of their status
Change-Id: I2cb1586fa1f88bab191af0ead22a2b8afca91a3b
=> Bug 1873449: Ensure proper cleanup of subports

kuryr_kubernetes/controller/drivers/network_policy.py, kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/controller/handlers/vif.py
There is a delay between namespace termination and having all the
objects from that namespace marked as being terminated. This means that
if on CRD creation we'll get a response stating that the namespace is
being terminated - we should ignore it, not fail. This commit makes sure
we only log a warning for those errors.
=> Bug 1874439: Ignore CRD creation errors when ns is terminated

kuryr_kubernetes/controller/handlers/loadbalancer.py, kuryr_kubernetes/tests/unit/controller/handlers/test_loadbalancer.py
When a Service is created before the Pods, no security group to be
enforced on the Load Balancer exists as no matching Pod, which are
the ones providing the sgs, is present yet. Consequently, the LB
gets created with admin_state down due to no sg present and ACLs
blocking the traffic. This commit ensures the LB sg crd holds the
updated Pods' sg before enforcing them on the LB members.
Closes-Bug: 1893910
Change-Id: I9eb52a4d6b82d70493d109e9eb9be8706142bc7d
=> Bug 1874504: Ensure LB sg is in sync with backend Pods

kuryr_kubernetes/controller/drivers/lb_public_ip.py, kuryr_kubernetes/controller/handlers/loadbalancer.py, kuryr_kubernetes/tests/unit/controller/drivers/test_lb_public_ip.py
When creating a Service of LoadBalancer type, a external_svc_net
config must be set, otherwise the Floating IP for the respective
LoadBalancer won't get created and an exception will be raised of
missing config. This commit logs and skip the FIP creation when
the needed config is not set.
Change-Id: I155d11f7080d2d4dbeca6de85b2f284aaacd7d8d
=> Bug 1874457: Skip FIP creation if no external subnet config is set

kuryr_kubernetes/controller/handlers/lbaas.py
If a loadBalancerIP is defined on the Service it should be used
on the created Load Balancer. However, that is not happening as
the LB CRD can be missing the lb_ip field  definition, consequently
a new Floating IP is allocated to the Load Balancer. This commit
fixes the issue by ensuring the lb_ip is present on the CRD if
defined on the Service.
Closes-Bug: 1893927
Change-Id: Ie626328972587772dbeeaf52f96b312de41026f2
=> Bug 1875352: Ensure loadBalancerIP is used when defined on the Service

kuryr_kubernetes/controller/drivers/namespace_subnet.py
Neutron clears device_owner when port is detached. This means that with
pools we need to consider ports without device_owner set when doing
cleanup on namespace deletion.
=> Bug 1873449: Delete ports without device_owner on ns deletion

kuryr_kubernetes/controller/drivers/network_policy.py, kuryr_kubernetes/controller/drivers/network_policy_security_groups.py, kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py
It may happen that between we list some resources and start iterating
through them, some get deleted. This commit makes sure we're ignoring
errors coming from such situations in NP code.
=> Bug 1875751: NP: Protect from disappearing resources

kuryr_kubernetes/controller/handlers/kuryrport.py, kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/controller/handlers/vif.py, kuryr_kubernetes/k8s_client.py, kuryr_kubernetes/tests/unit/controller/handlers/test_vif.py
It might happen, that during adding and instantly removing pod, vif
handler will not be able to set the finalizer for such object, resulting
in error. In this patch we prevent for such case.
Closes-Bug: 1894212
Change-Id: I5b3b4b36ae0c2fca7c16153f75c62607efbc3ce4
(cherry picked from commit f2e3ffb585a8c98f6994373dc66cac1c549ae659)
=> Bug 1867534: Catch exceptions for deleted pod.

kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/controller/handlers/loadbalancer.py, kuryr_kubernetes/exceptions.py, kuryr_kubernetes/k8s_client.py, kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py, kuryr_kubernetes/utils.py
When a lb transitions to ERROR or the IP on the Service
spec differs from the lb VIP, the lb is released and
the CRD doesn't get updated, causing Not Found expections
when handling the creation of others load balancer
resources. This commit fixes the issue by ensuring the
clean up of the status field happens upon lb release.
Also, it adds protection in case we still get
nonexistent lb on the CRD.
Closes-Bug: 1894758
Change-Id: I484ece6a7b52b51d878f724bd4fad0494eb759d6
=> Bug 1875491:Clean lb crd status upon Load Balancer removal

kubernetes_crds/kuryr_crds/kuryrloadbalancer.yaml, kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/controller/handlers/loadbalancer.py, kuryr_kubernetes/tests/unit/controller/handlers/test_loadbalancer.py
In theory with the usage of Finalizers having leaks of loadbalancers
is not possible anymore, and if the CRD is deleted it gets recreated
and also the loadbalancer is recreated.
This commit is deleting _cleanup_leftover_lbaas function and adapting
the code to recreate loadbalancers if the provider does not match.
Change-Id: I0db62a845b23a32eef4358368332c4da2cad5460
=> Bug 1876566: Leaks of loadbalancer

kuryr_kubernetes/exceptions.py, kuryr_kubernetes/k8s_client.py
During tests it turns out, that we didn't catch Forbidden exceptions,
since there was no forbidden http code sent from kubernetes API. In this
Patch we introduce new exception K8sFieldValueForbidden, which will be
raised on 422 Unprocessable Entity, k8s API returns.
Also, taken care of objects in state terminating in remove_finalizer
method.
Closes-Bug: 1895124
Change-Id: If4ac93190db3a56ee6b94ca122bfd2e95c29ffb9
=> Bug 1867534: Added new K8sFieldValueForbidden exception

images/iptables-scripts/ip6tables, images/iptables-scripts/iptables, openshift-kuryr-cni-rhel8.Dockerfile
This commit ensures iptables commands are
available on the containers, by relying on
the iptables utility installed on the host.
=> Bug 1878725: Add iptables wrappers to Kuryr CNI

kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
In OpenStackSDK, starting from version 0.18, there is a method available
for getting list for specified OpenStack service. In our case it is a
load balancer. In 3.11 however, we only have version 0.17 available
without that method causing container with kuryr-controller in
crashloop. This commit is fixing this in favor of directly looking at
Keystone catalogue.
=> Bug 1879855: Fix inability to determine Octavia version.

kuryr_kubernetes/controller/drivers/network_policy.py, kuryr_kubernetes/controller/drivers/vif_pool.py, kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/exceptions.py, kuryr_kubernetes/handlers/retry.py, kuryr_kubernetes/tests/unit/controller/drivers/test_vif_pool.py, kuryr_kubernetes/utils.py
This is another attempt at getting the useless tracebacks out of logs
for any level higher than debug. In particular:
* All pools logs regarding "Kuryr-controller not yet ready to *" are now
on debug level.
* The ugly ResourceNotReady raised from _populate_pool is now suppressed
if method is run from eventlet.spawn(), which prevents that exception
being logged by eventlet.
* ResourceNotReady will only print namespace/name or name, not the full
resource representation.
* ConnectionResetError is suppressed on Retry handler level just as any
other K8sClientError.
=> Bug 1860030: Civilize logging vol 2

kuryr_kubernetes/constants.py, kuryr_kubernetes/controller/handlers/lbaas.py
Headless Service are not wired by Kuryr as it returns
directly the Pod's IPs behind the Service and do not
load-balance between them. This commit makes sure a klb
CR is not created for headless services as a LB won't
get created for it.
Change-Id: Ib389ddd5edca44c713149adc13486ab0b08007d2
=> Bug 1881931: Skip KuryrLoadbalancer creation for Headless Service

kuryr_kubernetes/k8s_client.py
It may be possible that add_finalizer function first fails due
to a Conflict updating the object as it got updated (in this case
triggered the deletion) from the Kubernetes side, and then when
trying to get the new object this is actually gone as the deletion
was completed in between both actions. If that is the case we just
need to return false as there is no need to add a finalizer for it
Change-Id: I118a7c01d98722af30435f4d091820c81e4e95e4
=> Bug 1883167: Avoid race when pod is deleted before finalizer is added

kuryr_kubernetes/controller/drivers/vif_pool.py
Due to the use of pools, there may be ports that belongs to pools
associated to deleted nodes. Thus those ports are wasted as they
cannot be used.
This patch regularly checks for ports associated to deleted
nodes/trunks which would have lost their device_owner (for the
nested case), and for ports associated to deleted nodes for the
neutron vif case, where device owner is set but binding information
should not be there anymore.
Change-Id: I26be958aa3c0b51eb1a296eb2b4ac7996bc3263c
=> Bug 1883166: Cleanup ports belonging to deleted nodes

kuryr_kubernetes/controller/drivers/lbaasv2.py
When user manually deletes the load balancer for one specific service
we need to recreate the load balanacer.
This commit makes sure that the load balancer is recreated when the
service is updated.
Change-Id: I47cf26bf50bba865d727221c8df09bce01a9935a
=> Bug 1883832: Ensure klb handler reacretes lb

kuryr_kubernetes/controller/drivers/lbaasv2.py
It's possible that while ensuring the listener,
the load balancer was not present anymore and
consequently there is not need to update the vip
port sg. This commit enforces that the update only
happens if a listener was created and the vip is
present.
Change-Id: I3f104062887626f7b374993b5466fc962ccca85a
=> Bug 1883565: Skip update of vip sg if lb is gone

kuryr_kubernetes/k8s_client.py, kuryr_kubernetes/tests/unit/test_k8s_client.py
We're often contacting the K8s API through a loadbalancer (e.g. Octavia
LB in DevStack deployments, HAProxy in OpenShift) and we've often seen
they're able to drop connections silently, effectively leaving our
requests hanging forever. This got fixed in `K8sClient.watch` which
helped a lot, but we now seem to see it happening with other requests.
In order to make sure we won't block processing events for a resource
forever due to that, this commit adds read timeout to all the methods in
K8sClient.
Closes-Bug: 1897893
Change-Id: If1846ec78abc0840e7aba04565b220a1d20e5dc9
=> Bug 1884139: Set read timeout for any request in K8sClient

openshift-kuryr-cni-rhel8.Dockerfile
Updating kuryr-cni builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/0b997d0add07947c7ca65baa44901a2d113fd0e9/images/kuryr-cni.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
=> Updating kuryr-cni builder & base images to be consistent with ART

openshift-kuryr-controller-rhel8.Dockerfile
Updating kuryr-controller builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/ac81dd4ff0bd57c4e75058d25b40615b92948259/images/kuryr-controller.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
=> Updating kuryr-controller builder & base images to be consistent with ART

kuryr_kubernetes/controller/drivers/vif_pool.py
This patch adds protection for some problems in Neutron side:
- Ports created without IPs
- Detached subports that do not have its device_owner reset
Change-Id: Ia386274fe5c491432140a770cdd0b1beb969ac24
=> Bug 1884655: Add protection from unexpected issues

kuryr_kubernetes/controller/drivers/vif_pool.py, kuryr_kubernetes/exceptions.py, kuryr_kubernetes/handlers/retry.py, kuryr_kubernetes/tests/unit/controller/drivers/test_vif_pool.py, kuryr_kubernetes/utils.py
This is another attempt at getting the useless tracebacks out of logs
for any level higher than debug. In particular:
* All pools logs regarding "Kuryr-controller not yet ready to *" are now
on debug level.
* The ugly ResourceNotReady raised from _populate_pool is now suppressed
if method is run from eventlet.spawn(), which prevents that exception
being logged by eventlet.
* ResourceNotReady will only print namespace/name or name, not the full
resource representation.
* ConnectionResetError is suppressed on Retry handler level just as any
other K8sClientError.
Change-Id: Ic6e6ee556f36ef4fe3429e8e1e4a2ddc7e8251dc
=> Bug 1860311: Civilize logging vol 2

kuryr_kubernetes/k8s_client.py, kuryr_kubernetes/tests/unit/test_k8s_client.py
We're often contacting the K8s API through a loadbalancer (e.g. Octavia
LB in DevStack deployments, HAProxy in OpenShift) and we've often seen
they're able to drop connections silently, effectively leaving our
requests hanging forever. This got fixed in `K8sClient.watch` which
helped a lot, but we now seem to see it happening with other requests.
In order to make sure we won't block processing events for a resource
forever due to that, this commit adds read timeout to all the methods in
K8sClient.
Manual cherry-pick of #359
Closes-Bug: 1897893
Change-Id: If1846ec78abc0840e7aba04565b220a1d20e5dc9
=> Bug 1884192: Set read timeout for any request in K8sClient

kuryr_kubernetes/controller/drivers/utils.py
Seems like due to a mistake we've made is_host_network utility function
to always return False. This means that we considered hostNetworking
pods as regular one, ending up creating additional unused ports. Besides
that some anomalies regarding network policy could occur too as function
is used there.
=> Bug 1886871: Fix is_host_network() 

cni_ds_init
Recently we made some changes to naming of CNI configurations in the
RPM. This commit makes sure cni_ds_init script looks for them in correct
location.
=> Make cni_ds_init find correct conflist files

kuryr_kubernetes/controller/drivers/utils.py, kuryr_kubernetes/controller/handlers/kuryrport.py, kuryr_kubernetes/controller/handlers/vif.py
Due to bug 1899182 we were creating KuryrPorts and in consequence
Neutron ports for host networking pods. This is totally unnecessary and
those ports were not used at all. This commit makes sure even if version
with the bug was run, on kuryr-controller update those ports will get
deleted automatically.
=> Bug 1894194: Delete ports created for host networking pods

kuryr_kubernetes/controller/drivers/network_policy.py
While handling the creation of a Network
Policy it's possible that the CRD is patched
with repeated sg rules, which is not allowed
resulting in validation error as the repeated
sg rules will not have the sg rule id.
Closes-Bug: #1887167
Change-Id: Ia7814ddcea0d6948ff280a3e03a896bbc442891c
=> Bug 1893996: Fix duplicated sg rules on NP crd

kuryr_kubernetes/controller/drivers/utils.py, kuryr_kubernetes/tests/unit/controller/drivers/test_utils.py
match_selector() has a bug causing it to return True for any
podSelector with any matchLabel and pods without labels at all. This is
totally incorrect, casues issues like applying NPs to pods that should
not be affected by them and probably others.
=> Bug 1884584: Handle None or {} labels in match_selector() 

kuryr_kubernetes/controller/managers/prometheus_exporter.py, kuryr_kubernetes/tests/unit/controller/managers/test_prometheus_exporter.py
The calculation of the number of Ports available in a Subnet is
current relying on the allocation range to verify the number of
Ports available. That range does not include the gateway Port.
However, when listing the Port in use we're are taking into account
the gateway Port, resulting in not more ports left when still there
is one. This commit fixes the issue by not including the gateway IP
on the calculation.
=> Fix calculation of Ports availability in Subnet

kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/controller/handlers/loadbalancer.py, kuryr_kubernetes/tests/unit/controller/handlers/test_loadbalancer.py
This patch ensures that endpoints scale down to 0 event is handled
and therefore members are deleted from the loadbalancer pool
Change-Id: Idb879245607a6f0f914a44220312d54aa40e2e3d
Closes-Bug: 1904395
=> Bug 1897142: Ensure members are deleted from pools when there is no endpoints

kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/tests/unit/controller/handlers/test_lbaas.py
This patch ensures that endpoints scale down to 0 event is handled
and therefore members are deleted from the loadbalancer pool
Change-Id: I235ecaeb88b3990e0ef5bf27e2d878d415a3aceb
Closes-Bug: 1904395
=> Bug 1898906: Ensure members are deleted from pools when there is no endpoints

openshift-kuryr-kubernetes-rhel8.spec
pyroute2 0.5.6 is leaking processes, causing kuryr-cni to die occasionally.
This commit forces at least 0.5.7 which has the bug fixed.
=> Bug 1891559: Force pyroute2 0.5.7

kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/controller/handlers/lbaas.py
The openstacksdk version used (0.17.2) does
not support tags for loadbalancer. However, the
Octavia API does and the loadbalancers are
created with a tag. This commit ensures the
loadbalancer can be also filtered with tags
allowing the needed loadbalancers to get cleaned
up.
=> Bug 1896696: Ensure leftover loadbalancer is cleaned up

kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/tests/unit/controller/handlers/test_lbaas.py
This patch ensures that endpoints scale down to 0 event is handled
and therefore members are deleted from the loadbalancer pool
Cherry-pick #407
=> Bug 1900491: Ensure members are deleted from pools when there is no endpoints

kuryr_kubernetes/controller/managers/prometheus_exporter.py, kuryr_kubernetes/tests/unit/controller/managers/test_prometheus_exporter.py
We should be considering only the Ports created by Kuryr
when checking availablity on the Subnet. This commit fixes
the issue by relying on Tags when filtering Ports.
=> Bug 1890630: Ensure Ports in use per Subnet calculation is correct

kuryr_kubernetes/controller/managers/prometheus_exporter.py, kuryr_kubernetes/tests/unit/controller/managers/test_prometheus_exporter.py
Reverts openshift/kuryr-kubernetes#421
=> Revert "Bug 1890630: Ensure Ports in use per Subnet calculation is correct"

kuryr_kubernetes/controller/managers/prometheus_exporter.py
This commit fixes the port usage on subnet, by
excluding from the amount of ports used the
ports not allocated on the subnet.
Depends-on: #422
=> Bug 1890630: Fix alert value for ports available on Subnet

kuryr_kubernetes/controller/drivers/utils.py, kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py
It may happen that there's an unscheduled pod matching a policy when NP
is getting deleted. In that case we'll get a traceback as pod has no
nodeName set. This commit fixes that by making sure we skip unscheduled
pods when detaching SGs from ports on NP deletion.
=> Bug 1904973: Skip unscheduled pods when deleting NPs

kuryr_kubernetes/controller/drivers/network_policy.py, kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy.py
Code comparing SGs to determine if they need to be deleted or created
was incorrect due to not taking 'id' field existence into account. This
commit fixes that. Also reenables NP gate to be voting.
Closes-Bug: 1906549
Change-Id: I78ce0bd6a19aaedd5ecfd9451cd871d8baa0f675
=> Bug 1901495: Correctly compare SG rules in NP code

kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py
This is follow up to dce5939c242d44417b74e00382fd0a08a8c34f7b, as
apparently same problem can happen on NP creation. This patch makes sure
we skip unscheduled pods there too.
=> Bug 1904973: Skip unscheduled pods when handling NP creation

kuryr_kubernetes/cni/binding/base.py, kuryr_kubernetes/cni/binding/bridge.py, kuryr_kubernetes/cni/binding/nested.py, kuryr_kubernetes/cni/daemon/service.py, kuryr_kubernetes/cni/plugins/k8s_cni_registry.py, kuryr_kubernetes/tests/unit/cni/plugins/test_k8s_cni_registry.py, kuryr_kubernetes/tests/unit/cni/test_binding.py, kuryr_kubernetes/tests/unit/cni/test_service.py
As cri-o is the 4.3+ default CRI we did a ton of fixes to mitigate changes in how CNI calls kuryr-cni. This PR tries to backport them into the 3.11 branch to improve cri-o support there.
=> Bug 1889946: Bunch of CNI fixes related to cri-o

kuryr_kubernetes/cni/daemon/service.py, kuryr_kubernetes/tests/unit/cni/test_service.py
Seems like a thread moving the metrics data into the service exposing
them in the Prometheus format was not constrained with any sleep. This
was causing increased CPU usage of kuryr-cni pods without a  real
reason to do it.
This commit solves that by rewriting the thread to use the common
multiprocessing queue pattern.
Change-Id: I0eacc37022fbf214c361dbc52b42281ffa5301fd
=> Bug 1920481: Decrease CPU usage of Prometheus exporter

doc/source/installation/containerized.rst, doc/source/installation/devstack/nested-macvlan.rst, doc/source/installation/devstack/nested-vlan.rst, doc/source/nested_vlan_mode.rst, kuryr_kubernetes/config.py, kuryr_kubernetes/constants.py, kuryr_kubernetes/controller/drivers/base.py, kuryr_kubernetes/controller/drivers/nested_vif.py, kuryr_kubernetes/controller/drivers/network_policy.py, kuryr_kubernetes/controller/drivers/node_subnets.py, kuryr_kubernetes/controller/handlers/loadbalancer.py, kuryr_kubernetes/controller/handlers/machine.py, kuryr_kubernetes/tests/unit/controller/drivers/test_nested_vif.py, kuryr_kubernetes/tests/unit/controller/drivers/test_node_subnets.py, kuryr_kubernetes/tests/unit/controller/handlers/test_loadbalancer.py, kuryr_kubernetes/tests/unit/controller/handlers/test_machine.py, kuryr_kubernetes/tests/unit/test_utils.py, kuryr_kubernetes/utils.py, releasenotes/notes/deprecate-worker-nodes-subnet-e452c84df5b5ed5c.yaml, setup.cfg, tools/generate_k8s_resource_definitions.sh
This set of patches catches Kuryr up with recently introduced ShiftOnStack ability to run additional nodes on separate subnets. In order to support it we needed to make sure `worker_nodes_subnets` option that accepts a list is introduced, as well as make sure we're actually able to listen for changes in OpenShift `Machine` objects in order to get the current set of `worker_nodes_subnets` in the most reliable way.
=> Bug 1915885: Support multiple nodes subnets

kuryr_kubernetes/controller/drivers/vif_pool.py, kuryr_kubernetes/tests/unit/controller/drivers/test_vif_pool.py
This combines two fixes to port pools issue - one is making sure to convert float values into int whenever possible which will make sure all the combinations of values in port pools config work. Second idea is to avoid calling Neutron on prepopulation and make sure we use faster OpenShift API to get required data when possible.
=> Bug 1924075: Fix port pools

kuryr_kubernetes/controller/drivers/network_policy.py, kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py, kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/controller/handlers/namespace.py, kuryr_kubernetes/controller/handlers/vif.py, kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy.py, kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrnetworkpolicy.py, kuryr_kubernetes/tests/unit/controller/handlers/test_namespace.py, kuryr_kubernetes/tests/unit/controller/handlers/test_vif.py
When moving from annotation to CRD a compatibility code was added
to allow user to upgrade from ussuri to victoria version. Now we are going
to upgrade to wallaby, so everyone should already use CRD and we
can remove the code.
=> Removing the upgrade code from Kuryr-Kubernetes repo

kuryr_kubernetes/controller/drivers/node_subnets.py, kuryr_kubernetes/tests/unit/controller/drivers/test_node_subnets.py
Turns out there's an OpenShift mode where it's required to actually
hardcode a worker_nodes_subnet as some nodes does not have the Machine
objects. This commit solves that by making sure that
[pod_vif_nested]worker_nodes_subnets are also added to whatever the
OpenShiftNodesSubnets driver detects.
=> Bug 1927244: OpenShift: Add configured subnets to the detected

kuryr_kubernetes/cni/binding/nested.py, openshift-kuryr-tester.Dockerfile
We've hit cases when openshift-node is passing empty string as CNI_NETNS
in CNI requests. This is against the CNI spec and causes us to try to
remove the host eth0 interface which fails hard. This commit makes sure
we don't attempt to remove leftover container interfaces when '' is
passed as CNI_NETNS.
=> Bug 1929170: CNI: Protect from '' being passed as CNI_NETNS

kuryr_kubernetes/controller/handlers/lbaas.py
If Pods exposed by the Service have readinessProbe it may happen that
the Endpoints object with a slice will get created for them but it will
only have `notReadyAddresses` and will be missing `addresses` field. We
don't handle that well resulting in controller in a crash loop
complaining on KeyError. This commit fixes that by defaulting
`addresses` lookups to empty list [].
=> Bug 1929216: Handle Endpoints missing `addresses` field

kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/controller/drivers/network_policy.py, kuryr_kubernetes/controller/drivers/utils.py
Seems like we misunderstood the NP API reference and default the
protocol to TCP when creating SGs for NPs that are supposed to open all
traffic. That is incorrect and we should not specify a protocol in such
cases. This commit fixes that.
=> Bug 1919398: Do not default protocol to TCP for allow-all NPs

kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
This commit gathers two LB handling fixes:
* If an LB goes into ERROR state on provisioning we'll delete it and
retry the event again.
* If we detect that Octavia ACLs are enabled we won't try accessing the
LB SG on listener deletion.
=> Bug 1918568: Fix LB handling with ACLs and ERROR state

kuryr_kubernetes/controller/drivers/lbaasv2.py
When deleting LB in ERROR status we need to make sure the event is
retried on order for the LB to get recreated. This commit makes sure
that happens by raising ResourceNotReady after deleting the LB.
=> Bug 1918568: Raise ResourceNotReady when deleting ERROR LB

kuryr_kubernetes/controller/handlers/kuryrnetwork_population.py, kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrnetwork_population.py
In case the kuryrnetwork_population handler is enabled
and a Namespace creation was triggered, it's possible that
the kuryrnetwork_population handler attempts to do its job
before the KuryrNetwork handles the CR update with status field.
This commit fixes this race by skipping the event for the
kuryrnetwork_population when no 'status' is present and
modifying the event to be handled on a on_present operation
since the on_added would only be triggered once.
=> Bug 1924075: Skip pool pre population if no Status is present on CRD

kuryr_kubernetes/cni/binding/nested.py
The infamous `NetlinkError: (17, 'File exists')` started to bug us again
due to changes in when cri-o is deleting network namespaces. This patch
is an ultimate brute-force attempt to fix the problem. The idea is that
on NetlinkError kuryr-daemon will iterate over *all* network namespaces
in the system and delete interfaces that have the conflicting VLAN ID.
Closes-Bug: 1892388
Change-Id: I6672ed0e0db99a91b68cc4d9e74a33d8a9bcf0ca
=> Bug 1937991: CNI: Lookup offending interface on NetlinkError

kuryr_kubernetes/controller/drivers/network_policy.py
Seems like we need special handling of headless services in NP code that
is to ignore them if they have "None" string as a clusterIP.
=> Bug 1938960: Ignore headless services in NP code

kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/controller/drivers/network_policy.py, kuryr_kubernetes/controller/drivers/utils.py
Seems like we misunderstood the NP API reference and default the
protocol to TCP when creating SGs for NPs that are supposed to open all
traffic. That is incorrect and we should not specify a protocol in such
cases. This commit fixes that.
Change-Id: Ie7936555ac794f10443e48908b7b5b2494525b7c
Closes-Bug: 1914380
=> Bug 1940141: Do not default protocol to TCP for allow-all NPs

kuryr_kubernetes/controller/handlers/loadbalancer.py
This patch is fixing the bug in which was problem to
delete pools without members. Instead deleting pools
kuryr-controller was restarting because of this.
=> Bug 1936342: kuryr-controller restarting after 3 days cluster running - pools without members

kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/controller/handlers/loadbalancer.py, kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py, kuryr_kubernetes/utils.py
This commit allows Kuryr to handle the default Kuberntes Service
and ensure the load balancer is created with the provider that is
configured. Firstly, Kuryr detects the existent lb upon upgrade,
and delete the Load Balancer, the operation is then retried and lb
is created.
=> Handle default Kubernetes Service

kuryr_kubernetes/controller/drivers/network_policy.py, kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy.py
This is a fix for a missing backport.
Change-Id: Ia3af9b99a27663530efa82ca77bdd7bd733c2284
=> Bug 1947343: NPs: Do not set ports for protocol-less SG rules

kuryr_kubernetes/controller/drivers/network_policy.py
For OVN Ocatvia provider we need to include service subnet as well,
otherwise we will end up in no connectivity to services from pods where
network policy which define egress to all namespaces was applied.
Change-Id: Ic1d1803c178a9b8375f2a08e021f0a046fd7ff02
Related-Bug: 1915008
(cherry picked from commit bfe2e259a82dc11056338529c7a01f15a3e002b8)
=> Bug 1921878:  Include service subnet to be open for namespaceSelector set to all.

kuryr_kubernetes/controller/handlers/loadbalancer.py
This patch is fixing the bug in which was problem after the status
field is deleted, kuryr-controller is crashing because of it.
So we need to check if status field is missing and add it to the
crd.
Also I add there fixes of another parts of code where probably
in the future could be similar problem is some parts of the CRD
would be missing.
=> Bug 1933880: Fixing bug, Kuryr-Controller crashes when it's missing the status

kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/controller/handlers/loadbalancer.py, kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
The listeners timeout are constantly updated with
Octavia default values, even if no annotation was
updated on the respective Service. The constant
execution of this task makes the Load Balancer
to be stuck with PENDING_UPDATE status. This commit
fixes the issue by ensuring the listener values
are only added to the CR once there was annotation
changes, also it enforces the default values of not
existence of the field to be the same.
This PR also includes a fix to avoid the listener timeout
update when that is not supported in Octavia.
=> Bug 1949480: Fix constant update of Listeners timeout

kuryr_kubernetes/cni/binding/bridge.py, kuryr_kubernetes/config.py, kuryr_kubernetes/controller/drivers/namespace_subnet.py
We should allow the user to config the mtu
for the namespace networks and for VIFs when
the bridge driver is used.
Change-Id: I1685e31825f15387b6486713ce007b62e915df28
=> Bug 1932114: Allow to config network MTU

kuryr_kubernetes/controller/drivers/network_policy.py, kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy.py, kuryr_kubernetes/utils.py
For simple case, when operator wants to open connection to all the
namespaces in the cluster, i.e.:
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
name: networkpolicy-example
spec:
podSelector: {}
policyTypes:
- Egress
- Ingress
egress:
- to:
- namespaceSelector: {}
there was false assumption, that we need to open it without any
restriction, while the truth is, that all we need to do is to open
egress network to all the namespaces within cluster.
Change-Id: Ibea039fa9c3b46b83e99237ce2ceb03f02d50727
Closes-Bug: 1915008
(cherry picked from commit 304bc1bc2a8724fc07660c6f7e163618dc2c2e27)
=> Bug 1952429: Narrow connection to the cluster only on namespaceSelector.

kuryr_kubernetes/controller/drivers/network_policy.py
For OVN Ocatvia provider we need to include service subnet as well,
otherwise we will end up in no connectivity to services from pods where
network policy which define egress to all namespaces was applied.
Change-Id: Ic1d1803c178a9b8375f2a08e021f0a046fd7ff02
Related-Bug: 1915008
(cherry picked from commit bfe2e259a82dc11056338529c7a01f15a3e002b8)
(cherry picked from commit bb55f676b868232adfb36b06794b79f54e1425e2)
=> Bug 1941941: Include service subnet to be open for namespaceSelector set to all.

kuryr_kubernetes/constants.py, kuryr_kubernetes/controller/drivers/network_policy.py, kuryr_kubernetes/controller/drivers/network_policy_security_groups.py, kuryr_kubernetes/controller/drivers/utils.py, kuryr_kubernetes/controller/handlers/kuryrnetwork.py, kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py, kuryr_kubernetes/controller/handlers/kuryrport.py, kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy.py, kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy_security_groups.py, kuryr_kubernetes/tests/unit/controller/drivers/test_utils.py, kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrnetwork.py, kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrport.py
In case of hairpin LB traffic (member of the LB calls the LB and the
request is directed back to the same member) OVN replaces the source-ip
of the request with the LB IP. This means that pods with network
policies applied may have that traffic blocked when it should be
allowed.
To fix that this commit makes sure that SGs used for NPs include ingress
rules for each of the Service in it's namespace. It's not ideal but
seems to be a fair compromise between opening as little traffic as
possible and increasing number of security groups and rules.
As this commit makes sure all the NPs in the namespaces are reanalyzed
every time a Service is created or deleted, a little fixes in order to
support that are also made.
=> Bug 1920532: Fix NPs for OVN LBs with hairpin traffic

kuryr_kubernetes/utils.py
Due to coding error I not only switched "used" with "limit" in our
quota check messages but also made it impossible for the check to fail.
This commit fixes it.
=> Bug 1957315: Fix readiness quota check

kuryr_kubernetes/controller/handlers/loadbalancer.py
If we're in the process of handling a KuryrLoadBalancer event and
somebody's tries to delete the `.status` field there, any update we do
on `.status` will result in 422 Unprocessable Entity returned from K8s
API. There's no sense in failing kuryr-controller in that case as the
update should trigger another event and Kuryr should be able to recover
by discovering all the resources and filling the status again.
This commit fixes that by making sure in such situation we stop
processing the event and make the handler wait for the next one.
As a consuequence KLB's 404 returned from patch operations is also
handled as hard stop for further processing of the KuryrLoadBalancer as
there's no point in creating or deleting Octavia resources if the LB is
destined to be cascade deleted.
Change-Id: …
=> Bug 1933880: Ignore 422 Unprocessable Entity on KLB patching

kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
In case a LB resource ends up with ERROR in the provisioning status
we must ensure the deletion and recreation of the resource.
Closes-bug: 1879371
Change-Id: I2531948ab6181cfa5049b54c78935c23f60173d2
=> Bug 1954353: Ensure LB resources with ERROR status are deleted

openshift-kuryr-cni-ci.Dockerfile, openshift-kuryr-cni.Dockerfile
golang 1.11 is unsupported, let's upgrade it.
=> Bug 1955024: CNI: Use golang 1.15 for building

kuryr_kubernetes/constants.py, kuryr_kubernetes/controller/drivers/network_policy.py, kuryr_kubernetes/controller/drivers/network_policy_security_groups.py, kuryr_kubernetes/controller/drivers/utils.py, kuryr_kubernetes/controller/handlers/kuryrnetwork.py, kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py, kuryr_kubernetes/controller/handlers/kuryrport.py, kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy.py, kuryr_kubernetes/tests/unit/controller/drivers/test_network_policy_security_groups.py, kuryr_kubernetes/tests/unit/controller/drivers/test_utils.py, kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrnetwork.py, kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrport.py
In case of hairpin LB traffic (member of the LB calls the LB and the
request is directed back to the same member) OVN replaces the source-ip
of the request with the LB IP. This means that pods with network
policies applied may have that traffic blocked when it should be
allowed.
To fix that this commit makes sure that SGs used for NPs include ingress
rules for each of the Service in it's namespace. It's not ideal but
seems to be a fair compromise between opening as little traffic as
possible and increasing number of security groups and rules.
As this commit makes sure all the NPs in the namespaces are reanalyzed
every time a Service is created or deleted, a little fixes in order to
support that are also made.
Change-Id: I7e0458c4071e4a43ab4d158429e05c67cd897a3c
Closes-Bug: 1923452
=> Bug 1963846: Fix NPs for OVN LBs with hairpin traffic

kuryr_kubernetes/controller/drivers/lbaasv2.py
It's possible that the Listener timeouts data was
included in the CRD status, even though there is
no annotation on the Service, probably the Listener
was not present on the CRD, but created and the
controller attempts to find it and includes the timeouts
value. The timeouts included on the CRD then differs
from the spec values causing the constant update
of the Listener. This commit fixes the issue by ensuring
the timeouts information is only included on the CRD
when there was annoation(s) on the Service.
Closes-bug: 1930220
Change-Id: Iaaa6805287c175de618e0ec20099887f129e7536
=> Bug 1968436: Fix Listener timeouts update

kuryr_kubernetes/cni/handlers.py, kuryr_kubernetes/controller/drivers/base.py, kuryr_kubernetes/controller/drivers/nested_dpdk_vif.py, kuryr_kubernetes/controller/drivers/nested_macvlan_vif.py, kuryr_kubernetes/controller/drivers/nested_vlan_vif.py, kuryr_kubernetes/controller/drivers/neutron_vif.py, kuryr_kubernetes/controller/drivers/sriov.py, kuryr_kubernetes/controller/drivers/vif_pool.py, kuryr_kubernetes/controller/handlers/kuryrnetwork.py, kuryr_kubernetes/controller/handlers/kuryrnetwork_population.py, kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py, kuryr_kubernetes/controller/handlers/kuryrport.py, kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/controller/handlers/loadbalancer.py, kuryr_kubernetes/controller/handlers/machine.py, kuryr_kubernetes/controller/handlers/namespace.py, kuryr_kubernetes/controller/handlers/pod_label.py, kuryr_kubernetes/controller/handlers/policy.py, kuryr_kubernetes/controller/handlers/vif.py, kuryr_kubernetes/handlers/k8s_base.py, kuryr_kubernetes/handlers/retry.py, kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrport.py, kuryr_kubernetes/tests/unit/handlers/test_retry.py
Neutron should make a subport that is already attached to a trunk ACTIVE
immediately. Unfortunately there seems to be an OVN bug causing an event
triggering this to be lost, leaving the port in DOWN state forever. This
is a disaster for Kuryr, because we can't proceed to wire the pods in
such case.
This commit attempts to workaround this by making Kuryr reattach the
ports that are in DOWN state for more than 90 seconds after they're
plugged.
=> Bug 1969397: Workaround OVN bug causing subports to be DOWN

kuryr_kubernetes/controller/handlers/loadbalancer.py
=> [release-4.6] Bug 1968418: Fixing bug, Kuryr-Controller crashes when it's missing the status

kuryr_kubernetes/cmd/gather_openstack_data.py
must-gather gets the listings of the OpenStack resources in the project
Kuryr has access to and saves them. Somehow we skipped the secondary
Octavia resources from there. This commit fixes it.
Change-Id: I433dae5e345bf707df7da7b58492e72090a5d6c5
=> Add listeners, pools and members to must-gather

kuryr_kubernetes/cni/handlers.py, kuryr_kubernetes/controller/drivers/base.py, kuryr_kubernetes/controller/drivers/nested_dpdk_vif.py, kuryr_kubernetes/controller/drivers/nested_macvlan_vif.py, kuryr_kubernetes/controller/drivers/nested_vlan_vif.py, kuryr_kubernetes/controller/drivers/neutron_vif.py, kuryr_kubernetes/controller/drivers/sriov.py, kuryr_kubernetes/controller/drivers/vif_pool.py, kuryr_kubernetes/controller/handlers/kuryrnetwork.py, kuryr_kubernetes/controller/handlers/kuryrnetwork_population.py, kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py, kuryr_kubernetes/controller/handlers/kuryrport.py, kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/controller/handlers/loadbalancer.py, kuryr_kubernetes/controller/handlers/machine.py, kuryr_kubernetes/controller/handlers/namespace.py, kuryr_kubernetes/controller/handlers/pod_label.py, kuryr_kubernetes/controller/handlers/policy.py, kuryr_kubernetes/controller/handlers/vif.py, kuryr_kubernetes/handlers/k8s_base.py, kuryr_kubernetes/handlers/retry.py, kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrport.py, kuryr_kubernetes/tests/unit/handlers/test_retry.py
Neutron should make a subport that is already attached to a trunk ACTIVE
immediately. Unfortunately there seems to be an OVN bug causing an event
triggering this to be lost, leaving the port in DOWN state forever. This
is a disaster for Kuryr, because we can't proceed to wire the pods in
such case.
This commit attempts to workaround this by making Kuryr reattach the
ports that are in DOWN state for more than 90 seconds after they're
plugged.
Change-Id: If9a3968d68dced588614cd5521d4a111e78d435f
=> Bug 1972631: Workaround OVN bug causing subports to be DOWN

kuryr_kubernetes/cni/handlers.py, kuryr_kubernetes/controller/drivers/base.py, kuryr_kubernetes/controller/drivers/nested_dpdk_vif.py, kuryr_kubernetes/controller/drivers/nested_macvlan_vif.py, kuryr_kubernetes/controller/drivers/nested_vlan_vif.py, kuryr_kubernetes/controller/drivers/neutron_vif.py, kuryr_kubernetes/controller/drivers/sriov.py, kuryr_kubernetes/controller/drivers/vif_pool.py, kuryr_kubernetes/controller/handlers/kuryrnetwork.py, kuryr_kubernetes/controller/handlers/kuryrnetwork_population.py, kuryr_kubernetes/controller/handlers/kuryrnetworkpolicy.py, kuryr_kubernetes/controller/handlers/kuryrport.py, kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/controller/handlers/loadbalancer.py, kuryr_kubernetes/controller/handlers/namespace.py, kuryr_kubernetes/controller/handlers/pod_label.py, kuryr_kubernetes/controller/handlers/policy.py, kuryr_kubernetes/controller/handlers/vif.py, kuryr_kubernetes/handlers/k8s_base.py, kuryr_kubernetes/handlers/retry.py, kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrport.py, kuryr_kubernetes/tests/unit/handlers/test_retry.py
Neutron should make a subport that is already attached to a trunk ACTIVE
immediately. Unfortunately there seems to be an OVN bug causing an event
triggering this to be lost, leaving the port in DOWN state forever. This
is a disaster for Kuryr, because we can't proceed to wire the pods in
such case.
This commit attempts to workaround this by making Kuryr reattach the
ports that are in DOWN state for more than 90 seconds after they're
plugged.
=> Bug 1975676: Workaround OVN bug causing subports to be DOWN

kuryr_kubernetes/controller/managers/prometheus_exporter.py, kuryr_kubernetes/tests/unit/controller/managers/test_prometheus_exporter.py, kuryr_kubernetes/utils.py
Includes a new Gauge metric that records the
number of members of load balancers considered
critical. The metric is labeled with the Name
of load balancer and pool name, and the amount
of members. Also includes an Enum with the
current state of the lb.
=> Expose critical lbs metrics

kuryr_kubernetes/controller/managers/prometheus_exporter.py, kuryr_kubernetes/handlers/retry.py
In Kuryr-kubernetes we mainly rely on two services: Neutron for ports
creating and Octavia for load balancers. Sometimes we observe that either
ports or load balancer hangs in some states indefinitely. In such case,
after we timeout, kuryr controller will crash, leaving ambiguous log
message.
In this patch we introduce two new Prometheus metrics - one for Port and
the other for load balancer, which will be updated during such
situation.
=> Added metrics for failures caused by OpenStack services.

kuryr_kubernetes/cni/daemon/service.py
If the registry manager is stopped while daemon server is still
processing requests, the pending requests fail and result in resource
leaks in ovs.
With this change, we wait for DaemonServer to finish processing before
shutting down the registry manager.
Closes-bug: 1856109
Change-Id: I37498ae7bf6a8b4b14afe53d1af3fb8823d589cf
Signed-off-by: Yash Gupta <y.gupta@samsung.com>
Co-Authored-By: Michał Dulko <mdulko@redhat.com>
=> gracefully exit daemonserver before registry exit

kuryr_kubernetes/controller/handlers/loadbalancer.py
When the endpoints subsets is empty and the
CR contains load balancer infomation on the
status the clean up of unused members should
be performed and right now it's not as we assume
subset is alwas present. This commit fixes the
issue by making empty list the default when
endpoint is not present.
=> Bug 1983107: Allow clean up of unused member

kuryr_kubernetes/controller/handlers/lbaas.py
There's a corner case in conversion of Endpoints and Services
annotations into KuryrLoadBalancer CRDs in which the endpointSlices
field is ommitted causing a kuryr-controller restart. While it seems to
be harmless as after restart EndpointsHandler will kick in and add the
missing field, it's still worth to fix the migration.
This commit does so by making sure endpointSlices object is added to the
KuryrLoadbalancer spec.
Change-Id: I746c5e32f57491e94b7c04639bd9631f3a3fa6fb
=> Bug 1983107: Fix KLB conversion from annotations

kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/tests/unit/controller/handlers/test_lbaas.py, kuryr_kubernetes/tests/unit/test_utils.py, kuryr_kubernetes/utils.py
Closes-Bug: 1939512
Change-Id: Ia0a9ae82c46a43a64c916194a272f0a85618fa34
(cherry picked from commit 164095b0e71bdb3712494e060ad880b9560c87aa)
=> Bug 1938282: Remove ep_slices from klb on endpoint delete event

openshift-kuryr-cni-ci.Dockerfile, openshift-kuryr-controller-ci.Dockerfile
Apparently we should not use Stein but Rocky as that's how 3.11 Kuryr is
built elsewhere.
Change-Id: I56f48a9973591fda4272b8904bd5f97ff09c551b
=> Switch dockerfiles to use Rocky's RDO

kuryr_kubernetes/clients.py, kuryr_kubernetes/controller/handlers/namespace.py, kuryr_kubernetes/controller/handlers/policy.py, kuryr_kubernetes/controller/handlers/vif.py, kuryr_kubernetes/controller/managers/health.py, kuryr_kubernetes/tests/unit/controller/managers/test_health.py, kuryr_kubernetes/tests/unit/kuryr_fixtures.py, kuryr_kubernetes/utils.py
With large scale environments >3k ports, the health checks fails due to the slowness in API response from OpenStack.
This only changes the checks so that they use quota client instead.
=> Bug 2002548: Fix health checks on large scale environments

openshift-kuryr-tester-rhel8.Dockerfile
virtualenv 20.8.0 pulls in setuptools 58 which is incompatible with some
of our deps. This commit pins virtualenv to earlier version to make sure
unit tests and pep8 works.
=> Bug 2005355: tox tests: Pin virtualenv to 20.7.2

kuryr_kubernetes/controller/drivers/namespace_subnet.py, kuryr_kubernetes/controller/drivers/utils.py, kuryr_kubernetes/controller/drivers/vif_pool.py
This prevents Kuryr Controller from CrashLoopBackoff in unexpected case where the port is still part of the trunk during `_cleanup_leftover_ports`
=> Bug 2002171: remove port from trunk on _cleanup_leftover_ports

openshift-kuryr-tester.Dockerfile
Due to Let's Encrypt CA certificate expiring recently we're hitting
issues when pip in kuryr-tester is trying to reach opendev.org to fetch
global upper-constraints.txt file. Apparently pip uses it's own CA
certificates and those got expired.
This commit attempts to solve it by forcing pip to use system's CA
certificates by modifying its global configuration.
=> Force pip to use distro's CA certs

cni.Dockerfile, controller.Dockerfile, tox.ini
Update the URL to the upper-constraints file to point to the redirect
rule on releases.openstack.org so that anyone working on this branch
will switch to the correct upper-constraints list automatically when
the requirements repository branches.
Until the requirements repository has as stable/xena branch, tests will
continue to use the upper-constraints list on master.
Change-Id: Icd3318bd9e0cbf25894ab2849223f19c53447654
=> Bug 2019721: Update TOX_CONSTRAINTS_FILE for stable/xena

kuryr_kubernetes/controller/drivers/utils.py, kuryr_kubernetes/controller/drivers/vif_pool.py
Due to a known Neutron issue it's possible
to have subports with DOWN status and upon
controller restart those subports with are
not taken into account when repopulating the
pools resulting in leftovers. This commit
ensures nodes_ports_cleanup thread detach the
Port from the Trunk and remove it from the
Trunk.
Change-Id: If106637c81a5566d7bea00561f5cf1b381f97f23
=> Bug 2020664: Ensure DOWN subports are cleaned up

kuryr_kubernetes/controller/drivers/neutron_vif.py, kuryr_kubernetes/controller/drivers/utils.py, kuryr_kubernetes/controller/drivers/vif_pool.py, kuryr_kubernetes/controller/handlers/pod_label.py
Right now the in use Ports info is retrieved
by looking for the Pods and then for each
KuryrPort correponding to the specific Pod,
which can increase the time to recover precreated
Ports upon restart. This commit fixes the issue
by collecting all the KuryrPorts at once.
=> Bug 2019886: Improve retrieval of Trunks info

kuryr_kubernetes/cni/daemon/service.py, kuryr_kubernetes/controller/drivers/neutron_vif.py, kuryr_kubernetes/controller/drivers/utils.py, kuryr_kubernetes/controller/drivers/vif_pool.py, kuryr_kubernetes/controller/handlers/pod_label.py, kuryr_kubernetes/exceptions.py, lower-constraints.txt, requirements.txt
We've discovered that running kuryr-daemon with [cni_daemon]worker_num=1
breaks pyroute2.IPDB's ability to correctly close threads, leading to a
process leak. This commit makes sure kuryr-daemon will fail to start
when worker_num <= 1.
This required a few more changes in order to make sure that when any
kuryr-daemon subservice dies, kuryr-daemon will shutdown too.
=> Bug 2018152: Do not start kuryr-daemon when worker_num <= 1 

tools/build-rpm-rhel8.sh
The RPM build script hardcoded using 4.6 OpenStack repository. While
this isn't too serious as 4.6 is pretty much the same as 4.10, it should
get fixed so that we won't have issues switching to OSP 17 repos in the
future. This commit makes sure the script derives repo version from the
argument passed to it, which is supposed to be the build version.
Change-Id: I5cc93cd8a38bb7fcf45bb71bc56b8dafb32ed7dd
=> RPM build: Get OpenStack repo version from arg

kuryr_kubernetes/controller/handlers/kuryrport.py, kuryr_kubernetes/controller/handlers/vif.py, kuryr_kubernetes/tests/unit/controller/handlers/test_vif.py, kuryr_kubernetes/tests/unit/test_utils.py, kuryr_kubernetes/utils.py
When the Pod has status Completed it has finalized
its job, consequently it's expected that Kuryr will
reclycle the Neutron Ports associated with it to be
used by other Pods. However, Kuryr is considering
Completed Pods as not scheduled and the event is skipped.
This commit fixes the issue by ensuring that Completed
Pods Ports recycle is done before checking for Scheduled
Pods.
Closes-Bug: #1945680
Change-Id: I23e7901fb016d59fa76762d1f24fee47974e72df
=> Bug 2022722: Make completed Pods Ports reusable

kuryr_kubernetes/controller/drivers/utils.py, kuryr_kubernetes/controller/drivers/vif_pool.py
Due to a known Neutron issue it's possible
to have subports with DOWN status and upon
controller restart those subports with are
not taken into account when repopulating the
pools resulting in leftovers. This commit
ensures nodes_ports_cleanup thread detach the
Port from the Trunk and remove it from the
Trunk.
Change-Id: If106637c81a5566d7bea00561f5cf1b381f97f23
=> Bug 2023731: Ensure DOWN subports are cleaned up

kuryr_kubernetes/controller/drivers/lbaasv2.py
We're moving this because we discovered that Octavia will not always
raise Conflict if you create an LB with the same IP.
If no VIP port got created for an LB, then Octavia will not have any
issue with creating another LB with the same IP.
Closes-Bug: 1947809
Change-Id: I26b911b30403c7ea5a35706b2fc80af499e91330
=> Bug 2018129: Ensure KLB is updated

kuryr_kubernetes/controller/handlers/kuryrport.py, kuryr_kubernetes/controller/handlers/vif.py, kuryr_kubernetes/tests/unit/controller/handlers/test_vif.py, kuryr_kubernetes/tests/unit/test_utils.py, kuryr_kubernetes/utils.py
When the Pod has status Completed it has finalized
its job, consequently it's expected that Kuryr will
reclycle the Neutron Ports associated with it to be
used by other Pods. However, Kuryr is considering
Completed Pods as not scheduled and the event is skipped.
This commit fixes the issue by ensuring that Completed
Pods Ports recycle is done before checking for Scheduled
Pods.
Closes-Bug: #1945680
Change-Id: I23e7901fb016d59fa76762d1f24fee47974e72df
=> Bug 2028396: Make completed Pods Ports reusable

kuryr_kubernetes/cni/daemon/service.py, kuryr_kubernetes/exceptions.py, lower-constraints.txt, requirements.txt
We've discovered that running kuryr-daemon with [cni_daemon]worker_num=1
breaks pyroute2.IPDB's ability to correctly close threads, leading to a
process leak. This commit makes sure kuryr-daemon will fail to start
when worker_num <= 1.
This required a few more changes in order to make sure that when any
kuryr-daemon subservice dies, kuryr-daemon will shutdown too.
Change-Id: I41afc6fa67abfff62d2f0017db508051a1e7edf4
=> Bug 2023383: Do not start kuryr-daemon when worker_num <= 1

kuryr_kubernetes/controller/handlers/kuryrport.py
Recently, there was Events feature added to the KuryrPort/vif handlers,
where in one case the ResourceNotReady exception needed be to handled
elsewhere, but on behalf of event handling we needed to catch it on
KuryrPort handler, but it wasn't raised causing to swallow up the
events, and slowing down ports acknowledge. This patch fixes this.
Change-Id: I203773de2b8c0d1b21ef3f722df7ed7da562a892
(cherry picked from commit 6bfe0582cf227510e6f41310fd370c35a743d932)
=> Bug 2034898: Added missing raise statement for not ready resource.

kuryr_kubernetes/controller/drivers/base.py, kuryr_kubernetes/controller/drivers/nested_vlan_vif.py, kuryr_kubernetes/controller/drivers/neutron_vif.py, kuryr_kubernetes/controller/drivers/vif_pool.py, kuryr_kubernetes/tests/unit/controller/drivers/test_nested_vlan_vif.py, kuryr_kubernetes/tests/unit/controller/drivers/test_neutron_vif.py, kuryr_kubernetes/tests/unit/controller/drivers/test_vif_pool.py
This commit proposes to limit the number of create ports
in bulk requests to 20, since Neutron takes long to handle
this requests when the Number of ports and parallel calls
increase.
=> Bug 2035333: Limit the number of concurrent create_ports requests

kuryr_kubernetes/controller/handlers/kuryrport.py, kuryr_kubernetes/controller/handlers/vif.py, kuryr_kubernetes/tests/unit/controller/handlers/test_vif.py, kuryr_kubernetes/tests/unit/test_utils.py, kuryr_kubernetes/utils.py
When the Pod has status Completed it has finalized
its job, consequently it's expected that Kuryr will
reclycle the Neutron Ports associated with it to be
used by other Pods. However, Kuryr is considering
Completed Pods as not scheduled and the event is skipped.
This commit fixes the issue by ensuring that Completed
Pods Ports recycle is done before checking for Scheduled
Pods.
Closes-Bug: #1945680
Change-Id: I23e7901fb016d59fa76762d1f24fee47974e72df
=> Bug 2041903: Make completed Pods Ports reusable

kuryr_kubernetes/controller/drivers/vif_pool.py, kuryr_kubernetes/tests/unit/controller/drivers/test_vif_pool.py
It's possible that a Pod had a nodeName configured and
Kuryr started handling it, but after a while it was not
scheduled in that node anymore. This impacts the processing
of the Pod event as there are steps in between that the
Pod object is retrieved again with possibly no nodeName
assigned, making the controller to constantly retry for an
event that should be ignored.
Closes-bug: 1956767
Change-Id: I123dc706e14aa3edae06a165d6c0c09e99ef28d6
=> Bug 2045065: Ignore Pod event if Pod is Pending with no Node set

kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/controller/handlers/loadbalancer.py, kuryr_kubernetes/tests/unit/controller/handlers/test_lbaas.py
During the refactoring to allow proper Events creation for Services,
we've lost ability to update KLBs .spec.provider when configuration is
changed to use another provider. This commit fixes it by making sure
.spec.provider mismatch with the configured provider triggers the .spec
update.
=> Bug 2051423: Update KLB .spec.provider when required

kuryr_kubernetes/cni/prometheus_exporter.py
With Kuryr the CNI requests can take a considerable
time given that it has to wait for a VIF from Neutron.
Let's increase the number of buckets to have more
meaningful data.
Change-Id: I74a1ef3139df0f989a5b7d4b2c72bd977b6e7a35
=> Bug 2070047: Increase cni_request_duration buckets

kuryr_kubernetes/constants.py, kuryr_kubernetes/controller/drivers/namespace_subnet.py, kuryr_kubernetes/controller/drivers/nested_vlan_vif.py, kuryr_kubernetes/controller/drivers/utils.py, kuryr_kubernetes/controller/drivers/vif_pool.py, kuryr_kubernetes/tests/unit/controller/drivers/test_nested_vlan_vif.py, kuryr_kubernetes/tests/unit/controller/drivers/test_vif_pool.py
During removal of Neutron resources, sometimes there could be hanging
orphaned ports. Till now, all the removal was done one by one which
slows down removing process. In this change there is introduced removing
port in parallel in five concurrently run workers.
Change-Id: I74842989784601325b6d8977da4bc936ceedbc0e
(cherry picked from commit e9fd3bb13463f4a11f76694222dfc4f727c658b9)
=> Parallelize ports removal.

kubernetes_crds/kuryr_crds/kuryrport.yaml, kuryr_kubernetes/cni/binding/base.py, kuryr_kubernetes/cni/daemon/service.py, kuryr_kubernetes/cni/plugins/k8s_cni_registry.py, kuryr_kubernetes/cni/utils.py, kuryr_kubernetes/constants.py, kuryr_kubernetes/controller/handlers/vif.py, kuryr_kubernetes/exceptions.py, kuryr_kubernetes/tests/unit/cni/plugins/test_k8s_cni_registry.py, kuryr_kubernetes/utils.py
Recent versions of cri-o and containerd are passing K8S_POD_UID as a CNI
argument, alongside with K8S_POD_NAMESPACE and K8S_POD_NAME. As both
latter variables cannot be used to safely identify a pod in the API
(StatefulSet recreates pods with the same name), we were prone to race
conditions in the CNI code that we could only workaround. The end effect
was mostly IP conflict.
Now that the UID argument is passed, we're able to compare the UID from
the request with the one in the API to make sure we're wiring the
correct pod. This commit implements that by making sure to move the
check to the code actually waiting for the pod to appear in the
registry. In case of K8S_POD_UID missing from the CNI request, API call
to retrieve Pod is used as a fallback.
We also know that this check doesn't …
=> Bug 1983056: CNI: Use K8S_POD_UID passed from CRI

kuryr_kubernetes/cni/daemon/service.py, kuryr_kubernetes/cni/daemon/watcher_service.py, kuryr_kubernetes/cni/handlers.py, kuryr_kubernetes/cni/plugins/k8s_cni_registry.py, kuryr_kubernetes/constants.py, kuryr_kubernetes/exceptions.py, kuryr_kubernetes/tests/unit/cni/plugins/test_k8s_cni_registry.py, kuryr_kubernetes/tests/unit/cni/test_handlers.py, kuryr_kubernetes/tests/unit/cni/test_service.py
It can happen that we get the CNI request, but pod gets deleted before
kuryr-controller was able to create KuryrPort for it. If kuryr-daemon
only watches for KuryrPort events it will not be able to notice that
and will wait until the timeout, which in effect doesn't play well with
some K8s tests.
This commit adds a separate Service that will watch on Pod events and if
Pod gets deleted we'll make sure to put a sentinel value (None) into the
registry so that the thread waiting for the KuryrPort to appear there
will know that it has to stop and raise an error.
=> Bug 1997120: CNI: Watch for deleted pods 

tox.ini
Current OpenStack release - Zed, drops support for Python 3.6. As we
still run 3.6 here, this commit makes sure to use stable/xena
upper-constraints.txt file when running unit tests to make sure
dependencies support Python 3.6.
=> Bug 2097246: Use upper-constraints.txt from stable/xena in UT

kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/tests/unit/controller/handlers/test_lbaas.py
According to [1] we're supposed to support "funny" Service IPs, which
means IPs with leading zeros. Unlike unix in general we should not parse
them as octal values, but rather treat them like without leading zeros.
This commit makes sure that we strip the zeros from both ClusterIP and
LoadBalancerIP before we put them into KuryrLoadBalancer struct. This
means that later on Octavia and Neutron will get values that they
support and will proceed with LB or FIP creation normally.
[1] https://github.com/kubernetes/kubernetes/blob/v1.24.1/test/e2e/network/funny_ips.go
=> Bug 2094801: Strip leading zeros from "funny" Service IPs

kuryr_kubernetes/clients.py, kuryr_kubernetes/handlers/retry.py, kuryr_kubernetes/tests/unit/test_clients.py
We shouldn't be failing on Neutron quota exceptions as Kuryr is not in a
position to ever solve that by restarting. Anyway because bulk create
method that we implemented raised a different exception, we failed to
ignore them for health checks.
This commit makes sure bulk create method raises ConflictException, so
that Retry handler will correctly handle it. Moreover the exception
handling there is improved to make sure we're reading error code instead
of error message.
=> Bug 2094816: Do not crash on Neutron quota exceptions

kuryr_kubernetes/controller/handlers/kuryrnetwork.py
If there was any SDK exception while adding Subnet to the Router
e.g. 504 Gateway Time-out, no router_id would be returned causing
the Kuryr controller to restart when trying to create an event with
the unbound variable router_id. This commit fixes the issue by
removing the variable.
Change-Id: Ib26fce6ccdc83c61821b54297a388d0acd2da2c7
=> Bug OCPBUGS-577: Fix unbound router_id variable while creating event

kubernetes_crds/kuryr_crds/kuryrport.yaml, kuryr_kubernetes/cni/binding/base.py, kuryr_kubernetes/cni/daemon/service.py, kuryr_kubernetes/cni/daemon/watcher_service.py, kuryr_kubernetes/cni/handlers.py, kuryr_kubernetes/cni/plugins/k8s_cni_registry.py, kuryr_kubernetes/cni/utils.py, kuryr_kubernetes/constants.py, kuryr_kubernetes/controller/handlers/vif.py, kuryr_kubernetes/exceptions.py, kuryr_kubernetes/tests/unit/cni/plugins/test_k8s_cni_registry.py, kuryr_kubernetes/tests/unit/cni/test_handlers.py, kuryr_kubernetes/tests/unit/cni/test_service.py, kuryr_kubernetes/utils.py
Recent versions of cri-o and containerd are passing K8S_POD_UID as a CNI
argument, alongside with K8S_POD_NAMESPACE and K8S_POD_NAME. As both
latter variables cannot be used to safely identify a pod in the API
(StatefulSet recreates pods with the same name), we were prone to race
conditions in the CNI code that we could only workaround. The end effect
was mostly IP conflict.
Now that the UID argument is passed, we're able to compare the UID from
the request with the one in the API to make sure we're wiring the
correct pod. This commit implements that by making sure to move the
check to the code actually waiting for the pod to appear in the
registry. In case of K8S_POD_UID missing from the CNI request, API call
to retrieve Pod is used as a fallback.
We also know that this check doesn't …
=> OCPBUGS-11828: CNI: Watch for deleted pods 

kuryr_kubernetes/controller/handlers/kuryrport.py, kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrport.py
There's argument number mismatch on release_vif() call while reverting port association. This commit fixes that.
=> OCPBUGS-11993: Fix VIF revert on KuryrPort status update error

kuryr_kubernetes/controller/drivers/base.py, kuryr_kubernetes/controller/drivers/nested_dpdk_vif.py, kuryr_kubernetes/controller/drivers/nested_macvlan_vif.py, kuryr_kubernetes/controller/drivers/nested_vlan_vif.py, kuryr_kubernetes/controller/drivers/neutron_vif.py, kuryr_kubernetes/controller/drivers/vif_pool.py, kuryr_kubernetes/controller/handlers/kuryrport.py, kuryr_kubernetes/tests/unit/controller/drivers/test_vif_pool.py, kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrport.py, kuryr_kubernetes/tests/unit/test_utils.py, kuryr_kubernetes/utils.py
We can easily imagine an user frustrated by his pod not getting deleted and opting to remove the finalizer from the Pod. If the cause of the deletion delay was the kuryr-controller being down, we end up with an orphaned KuryrPort. At the moment this causes crashes, which obviously it shouldn't. Moreover we should figure out how to clean up the Neutron port if that happens. This commit does so as explained below.
1. KuryrPort on_present() will trigger its deletion when it detects that Pod does not longer exist.
2. Turns out security_groups parameter passed to release_vif() was never used. I removed it from drivers and got rid of get_security_groups() call from on_finalize() as it's no longer necessary.
3. When we cannot get the Pod in KuryrPort on_finalize() we attempt to gather info …
=> [release-4.10] Bug OCPBUGS-2216: Cleanup KuryrPort when Pod is missing
