openshift/kuryr-kubernetes

kuryr_cni/main.go, kuryr_kubernetes/cni/daemon/service.py, kuryr_kubernetes/config.py, kuryr_kubernetes/controller/drivers/namespace_subnet.py, kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/controller/service.py, kuryr_kubernetes/k8s_client.py, kuryr_kubernetes/tests/unit/test_k8s_client.py, kuryr_kubernetes/tests/unit/test_watcher.py, kuryr_kubernetes/watcher.py
4f75a5e was required to get rid of merge conflicts.
=> Rebase kuryr

openshift-kuryr-cni-ci.Dockerfile, openshift-kuryr-cni.Dockerfile, openshift-kuryr-controller-ci.Dockerfile, openshift-kuryr-controller.Dockerfile
Seems like it makes building containers harder, so remove it.
=> Remove `yum update` from Dockerfiles

kuryr_kubernetes/controller/drivers/namespace_subnet.py, kuryr_kubernetes/controller/drivers/network_policy_security_groups.py, kuryr_kubernetes/controller/drivers/utils.py, kuryr_kubernetes/controller/handlers/kuryrnet.py, kuryr_kubernetes/tests/unit/controller/drivers/test_utils.py, kuryr_kubernetes/tests/unit/controller/handlers/test_kuryrnet.py
This PR solves two corner-cases that caused Kuryr code to produce unexpected exceptions and crashing.
=> Bug 1759095: Prevent Kuryr from restarting due to corner-cases

kuryr_kubernetes/controller/drivers/vif_pool.py
Seems like there's a race condition or bug in K8s that on DELETE events
we can end up with annotated pod that doesn't have `status.hostIP` field
set. This is problematic for NestedVIFPool driver that used it as one of
the pool key elements.
This patch solves that by looking up host IP through Neutron and trunks
info if the field is missing from the pod.
Change-Id: Ib477213bab7e09bf6520f60b31d7d30584d90199
Closes-Bug: 1848172
=> Bug 1762787: NestedVIFPool: React when status.hostIP is missing

kuryr_kubernetes/controller/drivers/base.py, kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py, kuryr_kubernetes/tests/unit/controller/handlers/test_ingress_lbaas.py, kuryr_kubernetes/tests/unit/controller/handlers/test_lbaas.py
Change-Id: I2d7dd14c3f05b0b1da6db7ac9b58731e34b593e6
=> bug 1784435: Lbaas deletion

kuryr_kubernetes/controller/handlers/namespace.py, kuryr_kubernetes/tests/unit/controller/handlers/test_namespace.py
Change-Id: I3500b11717f6eeeb5b5686a25f085d26900aa434
=> Bug 1781198: Ensure namespace are recreated upon a k8s client failure

kuryr_kubernetes/controller/handlers/policy.py
When multiple Network policies deletion affecting the
same pod happens at the same time, a Not Found exception
can be raised causing a controller restart. This commit
fixes the issue by ensuring the policy deletion is retried
and the sgs list is updated.
Change-Id: I55a0f81ab6e30ca672e3f3d4865aed3cd96a94d2
=> Bug 1787341: Protect from sg Not Found on multiple np enforcement

kuryr_kubernetes/controller/handlers/lbaas.py
Right now the lbaas name and the service name are compared when
identifying a load balancer that exist with no matching service.
This might cause a wrong lbaas deletion as the service and the lbaas
name might differ. This commit fixes the issue by ensuring the
cluster_ip field of the service is used to verify the existence
of a matching lbaas.
Change-Id: I4a32b8ce3bae68b406f23429f2ad895dd44c9842
=> Bug 1784435: Ensure only lb with no corresponding svc is cleaned up

kuryr_kubernetes/controller/drivers/vif_pool.py
Change-Id: Ie1d7fb2d7d62c1a43a32d513fdcbbb265bebff98
=> Bug 1789329: Fix more problem of changing size during dict iteration

kuryr_kubernetes/cmd/gather_openstack_data.py
This commit ensures the quota for the project is also gathered.
=> Gather quota information

kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
This is an manual cherry-pick of #259
=> [release-4.5] Bug 1843817: Ensure provider information is used when finding lbs

kuryr_kubernetes/cni/daemon/service.py, kuryr_kubernetes/cni/prometheus_exporter.py, kuryr_kubernetes/cni/utils.py, kuryr_kubernetes/config.py, kuryr_kubernetes/controller/handlers/vif.py, kuryr_kubernetes/controller/managers/prometheus_exporter.py, kuryr_kubernetes/controller/service.py, kuryr_kubernetes/tests/unit/cni/test_service.py, kuryr_kubernetes/tests/unit/controller/managers/test_prometheus_exporter.py, openshift-kuryr-kubernetes-rhel8.spec, requirements.txt
This commit export cni_requests_duration and quota_free_count
metrics to Prometheus.
=> Export Prometheus metrics

kuryr_kubernetes/cni/binding/nested.py, kuryr_kubernetes/cni/daemon/service.py, kuryr_kubernetes/cni/plugins/k8s_cni_registry.py, kuryr_kubernetes/tests/unit/cni/plugins/test_k8s_cni_registry.py, kuryr_kubernetes/tests/unit/cni/test_binding.py, kuryr_kubernetes/tests/unit/cni/test_service.py
This PR collects 3 patches related to fixing NetlinkError occasionally happening in kuryr-daemon.
=> Bug 1786298: Bunch of kuryr-daemon NetlinkError fixes

kuryr_kubernetes/cni/binding/nested.py, kuryr_kubernetes/tests/unit/cni/test_binding.py
The VLAN and macvlan nested drivers are using [binding]link_iface option
to get the port they should bind the subport to. This isn't ideal as
there's a single config for all kuryr-cni containers in the cluster, so
it's impossible to provide multiple interface names when e.g. different
VM images are used to run workers in the cluster.
In order to make behavior smarter this patch makes sure that when
aforementioned option is not set, kuryr-daemon will attempt to
autodetect the interface it should bind the subport to by trying to find
which iterface kubelet is bound to. This should work fine with OpenShift
setups. If such interface is not found, kuryr-daemon will choose first
non-loopback interface.
Implements: blueprint autodetect-nested-iface
=> Bug 1829517:  Attempt to autodetect interface in nested setups

kubernetes_crds/kuryr_crds/kuryrloadbalancer.yaml, kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/controller/handlers/loadbalancer.py, kuryr_kubernetes/tests/unit/controller/handlers/test_loadbalancer.py
This commit formats the KuryrLoadBalancer CRD to include
the structure of EndpointSlice.
Change-Id: I1e42578841effeb3778e8d729c181b89b84f62b7
=> Bug 1873058: Convert KuryrLoadBalancer subsets CRD to EndpointSlice

kuryr_kubernetes/controller/handlers/loadbalancer.py
When syncing the load balancer security group,
the klb crd is updated with the new security groups,
but the event proceeds to be handled with outdated sgs.
This commit ensures the klb crd resource is updated.
Change-Id: Ia7064bc4b599b8dc05572717f4d80acc03583c20
=> Bug 1876571: Ensure updated lb sgs is used on the CRD

kuryr_kubernetes/controller/drivers/vif_pool.py
Change-Id: I6bcf920bd9686c61f8783bcf000b0f12a1568e24
=> Bug 1883166: Ensure only kuryr ports are cleaned up

kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
It's possible that a LB member got created and not
updated on the CRD, while the corresponding Kubernetes
resource also got the name update. This commit
adds a protection for LB members creation ensuring
that in case conflict the member has the name
updated.
Change-Id: I4e8a78ac5bc69665fb05031000ff20ae57e16bf7
=> Bug 1882453: Ensure LB member is updated if a conflict happens

kuryr_kubernetes/controller/managers/prometheus_exporter.py, kuryr_kubernetes/tests/unit/controller/managers/test_prometheus_exporter.py
This PR is a combination if the two fixes needed: https://github.com/openshift/kuryr-kubernetes/pull/403, https://github.com/openshift/kuryr-kubernetes/pull/423
=> Bug 1897526: Fix ports count on subnet

kuryr_kubernetes/controller/drivers/lbaasv2.py, kuryr_kubernetes/tests/unit/controller/drivers/test_lbaasv2.py
It's possible that a LB member got created and not
updated on the CRD, while the corresponding Kubernetes
resource also got the name update. This commit
adds a protection for LB members creation ensuring
that in case conflict the member has the name
updated.
Change-Id: I4e8a78ac5bc69665fb05031000ff20ae57e16bf7
=> Bug 1939961: Ensure LB member is updated if a conflict happens

kuryr_kubernetes/controller/handlers/namespace.py
This commit ensures that the quota value for specific
resources are fetched as attributes and not as dicts.
=> Bug 2002548: Ensure quotas values are fetched as attributes

kuryr_kubernetes/cni/daemon/service.py
kuryr-daemon does not handle reaping of zombie child processes which are
not started by itself. But being PID 1 inside the docker container, it
is expected to execute waitpid() for all its children.
This change runs a thread that waits for any killed child processes,
effectively reaping any zombie processes. This fixes the problem of
zombie process accumulation on long running deployments.
Change-Id: I48a665b089bf2d09eec9909e300a64f6e15cbdfe
Closes-Bug: 1854134
Signed-off-by: Yash Gupta <y.gupta@samsung.com>
=> Bug 2013496: Reap zombie child processes in CNI daemon service

kuryr_kubernetes/controller/drivers/nested_vlan_vif.py
It seems like we weren't paying attention to VLAN ID management when
handling errors on bulk port create requests. This commit fixes that by
making sure VLAN IDs are released if that happens.
Interestingly, we haven't really seen this affecting too much as in case
of these error Kuryr would restart thanks to health checks. But once you
stop restarting, the VLAN ID pool may get exhausted pretty soon.
=> Bug 2028816: Fix VLAN ID management 

kuryr_kubernetes/clients.py, kuryr_kubernetes/cni/plugins/k8s_cni_registry.py, kuryr_kubernetes/controller/drivers/vif_pool.py, kuryr_kubernetes/controller/handlers/kuryrport.py, kuryr_kubernetes/controller/handlers/lbaas.py, kuryr_kubernetes/controller/handlers/loadbalancer.py, kuryr_kubernetes/controller/handlers/pipeline.py, kuryr_kubernetes/controller/handlers/vif.py, kuryr_kubernetes/exceptions.py, kuryr_kubernetes/handlers/logging.py, kuryr_kubernetes/handlers/retry.py, kuryr_kubernetes/k8s_client.py, kuryr_kubernetes/tests/unit/controller/drivers/test_vif_pool.py, kuryr_kubernetes/tests/unit/controller/handlers/test_lbaas.py, kuryr_kubernetes/tests/unit/controller/handlers/test_loadbalancer.py, kuryr_kubernetes/tests/unit/controller/handlers/test_pipeline.py, kuryr_kubernetes/tests/unit/controller/handlers/test_vif.py, kuryr_kubernetes/utils.py
This PR adds patches implementing Pod and Service events.
=> Pod and Services events
